"""Soortspecifieke Nederlandse verzorgingsgidsen - deel 2: tropisch
bladgroen (klimmers, ficussen, dracaena's, palmen e.d.).

Zelfde tuple-volgorde als part1.py: (licht, water geven,
luchtvochtigheid, temperatuur, bemesten, verpotten, problemen).
"""

GUIDES = {
    "Swiss Cheese Vine": (
        "Helder, indirect licht; een oost- of westraam is ideaal. Bij te weinig licht krijgen nieuwe bladeren minder gaten en worden de stelen lang.",
        "Geef water zodra de bovenste 2-3 cm droog is - in de zomer ongeveer eens per week, in de winter eens per 10-14 dagen. Laat geen water in de schotel staan.",
        "Houdt van iets hogere luchtvochtigheid (50%+); bij droge verwarmingslucht helpt een luchtbevochtiger of een schaaltje met water en kiezels.",
        "Ideaal 18-27°C; niet onder 15°C.",
        "Elke 2-4 weken in voorjaar en zomer met kamerplantenvoeding op halve sterkte.",
        "Om de 1-2 jaar in het voorjaar in luchtige aroidenmix (potgrond met schors en perliet). Geef een mosstok of rek om langs te klimmen; hangend kan ook.",
        "Gele bladeren = te veel water; bruine, knisperende randen = droge lucht. Let op trips en spint.",
    ),
    "Golden Pothos": (
        "Verdraagt weinig licht, maar groeit het mooist en blijft het meest geel-bont in helder, indirect licht. Felle middagzon verbrandt het blad.",
        "Laat de bovenste helft van de grond opdrogen; ongeveer eens per week in de zomer, eens per 2 weken in de winter. Slap hangende bladeren betekenen dorst en herstellen snel na water.",
        "Normale kamerlucht is prima; een hogere luchtvochtigheid geeft grotere bladeren.",
        "Ideaal 18-27°C; niet onder 12°C.",
        "Elke 2-4 weken in voorjaar en zomer met kamerplantenvoeding.",
        "Om de 1-2 jaar in gewone kamerplantengrond. Lange ranken kun je terugknippen; stekken wortelen binnen een paar weken in een glas water.",
        "Gele bladeren = te veel water; kale, lange ranken = te weinig licht; groen wordende bontheid eveneens.",
    ),
    "Marble Queen Pothos": (
        "Helder, indirect licht is nodig om de wit-groene marmering te behouden; bij te weinig licht wordt het blad groener. Geen felle middagzon.",
        "Laat de bovenste helft van de grond opdrogen; ongeveer eens per week in de zomer, eens per 2 weken in de winter.",
        "Normale kamerlucht is prima; iets hogere luchtvochtigheid voorkomt bruine randjes op de witte delen.",
        "Ideaal 18-27°C; niet onder 15°C.",
        "Elke 3-4 weken in voorjaar en zomer met kamerplantenvoeding op halve sterkte - groeit trager dan de groene Pothos.",
        "Om de 1-2 jaar in luchtige kamerplantengrond. Stekken wortelen makkelijk in water.",
        "Bruine vlekken op de witte delen = te veel zon of droge lucht; gele bladeren = te nat.",
    ),
    "Satin Pothos": (
        "Helder tot matig indirect licht; directe zon verbleekt de zilverstippen.",
        "Laat de bovenste 3-5 cm opdrogen; de dikke bladeren krullen een beetje in als de plant dorst heeft. Ongeveer eens per 7-10 dagen in de zomer.",
        "Houdt van gemiddelde tot hogere luchtvochtigheid.",
        "Ideaal 18-27°C; niet onder 15°C.",
        "Elke 3-4 weken in voorjaar en zomer met kamerplantenvoeding op halve sterkte.",
        "Om de 2 jaar in luchtige potgrond met perliet. Groeit mooi als hangplant of langs een mosstok.",
        "Gele bladeren en zwarte stelen = te nat. Krullende bladeren = dorst.",
    ),
    "Split-Leaf Philodendron": (
        "Helder, indirect licht met eventueel wat ochtendzon. Bij te weinig licht worden de bladeren minder diep ingesneden.",
        "Laat de bovenste 3-5 cm opdrogen; ongeveer eens per week in de zomer, eens per 2 weken in de winter.",
        "Houdt van hogere luchtvochtigheid; veeg de grote bladeren af en toe schoon.",
        "Ideaal 18-27°C; kan kortstondig koeler, maar niet onder 12°C.",
        "Elke 2-4 weken in voorjaar en zomer met kamerplantenvoeding.",
        "Om de 2 jaar in een grote, zware pot met luchtige aroidenmix. Wordt breed - geef hem ruimte. Luchtwortels niet afknippen; leid ze naar de grond.",
        "Gele onderste bladeren zijn deels natuurlijke veroudering; veel gele bladeren = te nat. Bruine randen = droge lucht.",
    ),
    "Philodendron Birkin": (
        "Helder, indirect licht is nodig voor de witte strepen; bij te weinig licht verdwijnt de tekening. Geen directe zon.",
        "Laat de bovenste 2-3 cm opdrogen; ongeveer eens per week in de zomer.",
        "Houdt van 50%+ luchtvochtigheid.",
        "Ideaal 18-27°C; niet onder 15°C.",
        "Elke 3-4 weken in voorjaar en zomer met kamerplantenvoeding op halve sterkte.",
        "Om de 1-2 jaar in luchtige aroidenmix. Groeit compact en rechtop.",
        "Terugvallen naar groene bladeren ('reverting') is normaal bij Birkin; knip volledig groene scheuten weg om de tekening te behouden.",
    ),
    "Pink Princess Philodendron": (
        "Veel helder, indirect licht voor de roze bontheid; geen directe middagzon, want de roze delen verbranden snel.",
        "Laat de bovenste 2-3 cm opdrogen; ongeveer eens per week in de zomer, minder in de winter.",
        "Houdt van 50-60% luchtvochtigheid.",
        "Ideaal 18-27°C; niet onder 15°C.",
        "Elke 3-4 weken in voorjaar en zomer met kamerplantenvoeding op halve sterkte.",
        "Om de 1-2 jaar in luchtige aroidenmix; geef een mosstok om te klimmen.",
        "Bruine, droge roze plekken zijn normaal (die delen hebben geen bladgroen). Worden nieuwe bladeren groen, knip dan terug tot een blad met veel roze.",
    ),
    "Philodendron Xanadu": (
        "Helder, indirect licht; verdraagt wat ochtendzon. Bij te weinig licht worden de bladstelen lang.",
        "Laat de bovenste 3-5 cm opdrogen; ongeveer eens per week in de zomer.",
        "Normale tot hogere luchtvochtigheid.",
        "Ideaal 18-27°C; niet onder 12°C.",
        "Elke 2-4 weken in voorjaar en zomer met kamerplantenvoeding.",
        "Om de 2 jaar in een brede pot met luchtige potgrond; groeit als een brede pol, niet klimmend.",
        "Gele bladeren = te nat; bruine bladpunten = droge lucht of te veel voeding.",
    ),
    "Arrowhead Plant": (
        "Helder, indirect licht; bonte en roze vormen hebben meer licht nodig dan groene. Geen directe zon.",
        "Houd de grond licht vochtig en geef water zodra de bovenste 2 cm droog is - ongeveer eens per week in de zomer.",
        "Houdt van 50%+ luchtvochtigheid.",
        "Ideaal 18-26°C; niet onder 15°C.",
        "Elke 2-4 weken in voorjaar en zomer met kamerplantenvoeding op halve sterkte.",
        "Om de 1-2 jaar in luchtige potgrond. Knip klimmende ranken terug als je de compacte pijlvormige bladeren wilt houden.",
        "Bruine randen = droge lucht; gele bladeren = te nat. Let op spint en trips.",
    ),
    "Dragon Tree": (
        "Helder, indirect licht; verdraagt minder licht, maar dan verbleekt de rode rand. Geen felle middagzon.",
        "Laat de bovenste helft van de grond opdrogen; ongeveer eens per 1-2 weken in de zomer, eens per 3 weken in de winter.",
        "Normale kamerlucht is prima.",
        "Ideaal 18-26°C; niet onder 12°C.",
        "Eens per maand in voorjaar en zomer met kamerplantenvoeding.",
        "Om de 2-3 jaar in potgrond met extra perliet. Te lange stammen kun je inkorten; de stomp loopt weer uit.",
        "Bruine bladpunten komen vaak door fluoride of kalk in kraanwater - gebruik regenwater of gefilterd water. Gele onderste bladeren die afvallen zijn normaal.",
    ),
    "Corn Plant": (
        "Helder, indirect licht; verdraagt minder licht, maar bonte vormen verliezen dan hun streep.",
        "Laat de bovenste 3-5 cm opdrogen; ongeveer eens per 1-2 weken in de zomer, eens per 3 weken in de winter.",
        "Houdt van gemiddelde luchtvochtigheid; stof de bladeren af en toe af.",
        "Ideaal 18-26°C; niet onder 12°C.",
        "Eens per maand in voorjaar en zomer met kamerplantenvoeding.",
        "Om de 2-3 jaar in potgrond met perliet in een zware pot.",
        "Bruine bladpunten en -randen = kalk/fluoride in water, droge lucht of te veel voeding. Zachte stam = rot door te veel water.",
    ),
    "Song of India": (
        "Veel helder, indirect licht voor de geel-groene strepen; wat ochtendzon is prima.",
        "Laat de bovenste 3-5 cm opdrogen; ongeveer eens per week in de zomer, minder in de winter.",
        "Houdt van gemiddelde tot hogere luchtvochtigheid.",
        "Ideaal 18-26°C; niet onder 13°C.",
        "Eens per maand in voorjaar en zomer met kamerplantenvoeding.",
        "Om de 2-3 jaar in potgrond met perliet; de slappe stammen kunnen steun nodig hebben.",
        "Afvallende bladeren na een verplaatsing zijn stress; bruine punten = hard water of droge lucht.",
    ),
    "Rubber Plant": (
        "Helder, indirect licht met eventueel wat ochtendzon; donkerbladige vormen verdragen iets minder licht, bonte vormen willen meer.",
        "Laat de bovenste 3-5 cm opdrogen; ongeveer eens per week in de zomer, eens per 2 weken in de winter.",
        "Normale kamerlucht is prima; veeg stof van de grote bladeren met een vochtige doek.",
        "Ideaal 18-27°C; niet onder 13°C en weg van tocht.",
        "Elke 2-4 weken in voorjaar en zomer met kamerplantenvoeding.",
        "Om de 1-2 jaar in het voorjaar in potgrond met perliet. Top de plant om hem vertakt te laten groeien; het witte melksap irriteert de huid.",
        "Bladval na verplaatsen of tocht is een stressreactie. Gele, afvallende onderste bladeren = te nat; bruine vlekken = te koud of zonnebrand.",
    ),
    "Fiddle Leaf Fig": (
        "Veel helder licht, het liefst direct bij een oost- of zuidraam met wat ochtendzon. Draai de pot niet te vaak - de plant past zich langzaam aan.",
        "Laat de bovenste 3-5 cm opdrogen en geef dan grondig water; ongeveer eens per 7-10 dagen in de zomer, eens per 2 weken in de winter.",
        "Houdt van 40-60% luchtvochtigheid; veeg de grote bladeren regelmatig schoon.",
        "Ideaal 18-27°C; zeer gevoelig voor tocht en koude ramen.",
        "Elke 2-4 weken in voorjaar en zomer met kamerplantenvoeding (liefst een speciale ficusvoeding).",
        "Om de 1-2 jaar in het voorjaar in goed drainerende potgrond met perliet. Zet de plant daarna niet meer onnodig om.",
        "Bruine vlekken midden op het blad = te veel water/wortelrot; bruine, droge randen = te droog; bladval = verplaatsing of tocht.",
    ),
    "Weeping Fig": (
        "Helder licht met eventueel wat ochtendzon; kies één vaste, lichte plek en laat hem daar staan.",
        "Laat de bovenste 2-3 cm opdrogen; ongeveer eens per week in de zomer, minder in de winter.",
        "Houdt van gemiddelde luchtvochtigheid; droge lucht geeft spint.",
        "Ideaal 18-26°C; niet onder 15°C en zonder tocht.",
        "Elke 2-4 weken in voorjaar en zomer met kamerplantenvoeding.",
        "Om de 2 jaar in het voorjaar in potgrond met perliet. Snoeien in het voorjaar houdt de kroon compact.",
        "Plotselinge bladval komt bijna altijd door verplaatsen, tocht of een wisseling in licht - de plant groeit daarna meestal vanzelf weer bij.",
    ),
    "Audrey Ficus": (
        "Veel helder licht; verdraagt ook een paar uur directe zon. Minder kieskeurig dan de Vioolbladplant.",
        "Laat de bovenste 3-5 cm opdrogen; ongeveer eens per week in de zomer, eens per 2 weken in de winter.",
        "Normale kamerlucht is prima.",
        "Ideaal 18-27°C; niet onder 13°C.",
        "Elke 2-4 weken in voorjaar en zomer met kamerplantenvoeding.",
        "Om de 1-2 jaar in het voorjaar in potgrond met perliet.",
        "Bladval na verplaatsen is normaal; gele bladeren = te nat. Let op schildluis op de bladnerven.",
    ),
    "Umbrella Tree": (
        "Helder, indirect licht; bonte vormen hebben meer licht nodig. Bij te weinig licht wordt de plant lang en kaal.",
        "Laat de bovenste 2-3 cm opdrogen; ongeveer eens per week in de zomer, eens per 2 weken in de winter.",
        "Normale kamerlucht is prima; bij droge lucht is spint een risico.",
        "Ideaal 16-24°C; verdraagt het koeler dan veel tropische planten, niet onder 12°C.",
        "Elke 2-4 weken in voorjaar en zomer met kamerplantenvoeding.",
        "Om de 2 jaar in het voorjaar in potgrond met perliet. Snoei gerust terug om de plant vol te houden.",
        "Bladval = te nat of te donker; fijne webjes en gespikkelde bladeren = spint (douche de plant af).",
    ),
    "Baby Rubber Plant": (
        "Helder, indirect licht; bonte vormen hebben meer licht nodig. Geen felle middagzon.",
        "De dikke bladeren slaan water op: laat de bovenste helft van de grond opdrogen. Ongeveer eens per 1-2 weken in de zomer.",
        "Normale kamerlucht is prima.",
        "Ideaal 18-25°C; niet onder 15°C.",
        "Eens per maand in voorjaar en zomer met kamerplantenvoeding op halve sterkte.",
        "Kleine wortels: verpot om de 2-3 jaar in een kleine pot met luchtige grond (potgrond + perliet).",
        "Slappe, zachte stengels = te veel water; zwarte vlekken op het blad = koude of te nat.",
    ),
    "Emerald Ripple Peperomia": (
        "Helder, indirect licht; geen directe zon.",
        "Laat de bovenste 2-3 cm opdrogen; giet op de grond, niet in het hart van de plant. Ongeveer eens per 7-10 dagen in de zomer.",
        "Houdt van iets hogere luchtvochtigheid.",
        "Ideaal 18-24°C; niet onder 15°C.",
        "Eens per maand in voorjaar en zomer met kamerplantenvoeding op halve sterkte.",
        "Verpot zelden; blijft klein. Gebruik luchtige grond met perliet.",
        "Rottende bladstelen in het hart = water in de plant gegoten of te nat. Een bladstek wortelt makkelijk.",
    ),
    "Watermelon Peperomia": (
        "Helder, indirect licht voor de zilveren strepen; directe zon verbleekt ze.",
        "Laat de bovenste 2-3 cm opdrogen; ongeveer eens per week in de zomer. De bladeren worden iets slap als hij dorst heeft.",
        "Houdt van 50%+ luchtvochtigheid.",
        "Ideaal 18-24°C; niet onder 15°C.",
        "Eens per maand in voorjaar en zomer met kamerplantenvoeding op halve sterkte.",
        "Om de 2 jaar in luchtige potgrond. Een blad met een stukje steel wortelt makkelijk als stek.",
        "Gebroken bladstelen komen vaak door de breekbare stelen; zachte, bruine stelen = te nat.",
    ),
    "Wax Plant": (
        "Helder licht met wat ochtend- of avondzon; zonder genoeg licht komt er geen bloei.",
        "Laat de grond grotendeels opdrogen - de vlezige bladeren slaan water op. In de zomer ongeveer eens per 1-2 weken, in de winter eens per 3 weken.",
        "Normale kamerlucht is prima; hogere luchtvochtigheid bevordert de bloei.",
        "Ideaal 18-25°C; een koelere winter (13-15°C) stimuleert bloei.",
        "Elke 2-4 weken in voorjaar en zomer met een fosforrijke bloeivoeding op halve sterkte.",
        "Verpot zelden: bloeit het best als de pot krap zit. Gebruik luchtige mix met schors/perliet.",
        "Knip de uitgebloeide bloemstengels niet af: daar komen volgend jaar opnieuw bloemen aan. Verplaats de plant niet als hij knoppen heeft - dan vallen ze af.",
    ),
    "Sweetheart Hoya": (
        "Helder licht met een paar uur zachte zon.",
        "De dikke hartvormige bladeren slaan veel water op: laat de grond helemaal opdrogen. Ongeveer eens per 2 weken in de zomer, eens per 3-4 weken in de winter.",
        "Normale kamerlucht is prima.",
        "Ideaal 18-26°C; niet onder 15°C.",
        "Eens per maand in voorjaar en zomer met kamerplantenvoeding op halve sterkte.",
        "Verpot zelden, in luchtige mix met schors en perliet. Losse hartjes zonder knoop groeien nooit uit tot een plant - voor een echte plant heb je een stek met knoop nodig.",
        "Zachte, gele bladeren = te nat. Groeit extreem langzaam, vooral als losse bladstek - dat is normaal.",
    ),
    "Spider Plant": (
        "Helder, indirect licht; verdraagt ook halfschaduw. Directe middagzon verbrandt de bladpunten.",
        "Houd de grond licht vochtig in de zomer (ongeveer eens per week) en laat hem in de winter iets meer opdrogen. De dikke wortels slaan water op.",
        "Normale kamerlucht is prima.",
        "Ideaal 15-24°C; verdraagt het koeler, tot ongeveer 7°C.",
        "Elke 2-4 weken in voorjaar en zomer met kamerplantenvoeding op halve sterkte.",
        "Verpot als de wortels de pot omhoog duwen (om de 1-2 jaar). De jonge plantjes aan de uitlopers kun je in een potje met grond zetten.",
        "Bruine bladpunten komen vaak door fluoride/kalk in kraanwater, droge lucht of te veel voeding - gebruik regenwater.",
    ),
    "Wandering Jew": (
        "Veel helder licht met wat ochtendzon voor de paars-zilveren kleur; bij te weinig licht vervaagt de tekening.",
        "Laat de bovenste 2 cm opdrogen; ongeveer eens per week in de zomer. Giet op de grond, niet over het blad.",
        "Normale kamerlucht is prima.",
        "Ideaal 16-24°C; niet onder 12°C.",
        "Eens per maand in voorjaar en zomer met kamerplantenvoeding op halve sterkte.",
        "Groeit snel en wordt onderaan kaal; knip regelmatig terug en zet de stekken terug in de pot voor een volle plant.",
        "Kale, lange ranken = te weinig licht of oude plant (vernieuwen via stek). Bruine, droge blaadjes = te droog of te droge lucht.",
    ),
    "Inch Plant": (
        "Helder, indirect licht; bonte vormen willen meer licht.",
        "Houd de grond licht vochtig; ongeveer eens per week in de zomer.",
        "Normale kamerlucht is prima.",
        "Ideaal 16-24°C.",
        "Eens per maand in voorjaar en zomer met kamerplantenvoeding op halve sterkte.",
        "Groeit zeer snel; knip regelmatig terug en stek de toppen opnieuw.",
        "Groene scheuten op een bonte plant weghalen; kale ranken = oude plant of weinig licht.",
    ),
    "Aluminum Plant": (
        "Helder, indirect licht; directe zon verbrandt de zilveren vlekken.",
        "Houd de grond licht vochtig; geef water zodra de bovenste 2 cm droog is.",
        "Houdt van 50%+ luchtvochtigheid.",
        "Ideaal 16-24°C; niet onder 12°C.",
        "Elke 2-4 weken in voorjaar en zomer met kamerplantenvoeding op halve sterkte.",
        "Groeit snel en wordt lang; top de scheuten regelmatig. Vernieuw de plant elke paar jaar via stek.",
        "Kale, lange stengels = te weinig licht of niet getopt; bladval = te droog of te koud.",
    ),
    "Chinese Evergreen": (
        "Groene vormen verdragen weinig licht goed; bonte en rode vormen willen helder, indirect licht. Geen directe zon.",
        "Laat de bovenste 2-3 cm opdrogen; ongeveer eens per week in de zomer, eens per 2 weken in de winter.",
        "Houdt van gemiddelde tot hogere luchtvochtigheid.",
        "Ideaal 18-27°C; kouder dan 15°C geeft schade aan het blad.",
        "Elke 4-6 weken in voorjaar en zomer met kamerplantenvoeding op halve sterkte.",
        "Groeit langzaam; verpot om de 2-3 jaar in luchtige potgrond.",
        "Bruine randen = droge lucht of koud; gele bladeren = te nat. Draag handschoenen: het sap irriteert.",
    ),
    "Croton": (
        "Veel licht met een paar uur directe zon; alleen dan blijven de gele, oranje en rode kleuren fel.",
        "Houd de grond licht vochtig; geef water zodra de bovenste 2 cm droog is.",
        "Houdt van 50%+ luchtvochtigheid; droge lucht geeft spint.",
        "Ideaal 18-27°C; zeer gevoelig voor kou en tocht (niet onder 15°C).",
        "Elke 2-4 weken in voorjaar en zomer met kamerplantenvoeding.",
        "Om de 2 jaar in het voorjaar in potgrond met perliet. Draag handschoenen: het melksap irriteert.",
        "Massale bladval na aankoop of verplaatsing is een bekende stressreactie. Groen wordende bladeren = te weinig licht.",
    ),
    "Ti Plant": (
        "Helder licht met wat directe ochtendzon voor de rode en roze kleuren.",
        "Houd de grond licht vochtig; ongeveer eens per week in de zomer. Gevoelig voor fluoride in kraanwater - regenwater is beter.",
        "Houdt van 50%+ luchtvochtigheid.",
        "Ideaal 18-27°C; niet onder 13°C.",
        "Elke 2-4 weken in voorjaar en zomer met kamerplantenvoeding.",
        "Om de 2 jaar in potgrond met perliet.",
        "Bruine bladpunten = fluoride/kalk of droge lucht; verbleekte kleuren = te weinig licht.",
    ),
    "English Ivy": (
        "Helder, indirect licht; bonte vormen willen meer licht. Verdraagt ook halfschaduw.",
        "Houd de grond licht vochtig; laat de bovenste 2 cm opdrogen voor je weer water geeft.",
        "Houdt van hogere luchtvochtigheid en koele lucht; in warme, droge kamers krijgt hij snel spint.",
        "Houdt van koel: 10-20°C. Een onverwarmde slaapkamer of hal is ideaal.",
        "Elke 2-4 weken in voorjaar en zomer met kamerplantenvoeding op halve sterkte.",
        "Om de 1-2 jaar in gewone potgrond. Knip regelmatig terug; stekken wortelen makkelijk.",
        "Spint (grijze, gespikkelde bladeren met fijne webjes) is het grootste probleem - douche de plant regelmatig af en zet hem koeler.",
    ),
    "Swedish Ivy": (
        "Helder, indirect licht met wat ochtendzon.",
        "Houd de grond licht vochtig; ongeveer eens per week in de zomer.",
        "Normale kamerlucht is prima.",
        "Ideaal 16-24°C.",
        "Elke 2-4 weken in voorjaar en zomer met kamerplantenvoeding op halve sterkte.",
        "Groeit snel; knip regelmatig terug voor een volle plant. Stekken wortelen makkelijk in water.",
        "Kale, lange ranken = te weinig licht; gele bladeren = te nat.",
    ),
    "Fatsia": (
        "Helder, indirect licht tot halfschaduw; geen felle middagzon.",
        "Houd de grond licht vochtig in de zomer; in een koele winter veel minder water geven.",
        "Normale kamerlucht; veeg de grote bladeren af en toe schoon.",
        "Houdt van koel: 10-20°C. In een warme kamer wordt hij slap; een koele hal of serre is ideaal.",
        "Elke 2-4 weken in voorjaar en zomer met kamerplantenvoeding.",
        "Om de 1-2 jaar in het voorjaar in gewone potgrond. Kan 's zomers buiten in de schaduw staan.",
        "Slap hangende bladeren = te warm of te droog; gele bladeren = te nat. Let op spint en wolluis.",
    ),
    "Kentia Palm": (
        "Verdraagt weinig licht goed, maar groeit het mooist in helder, indirect licht. Directe zon verbrandt de bladeren.",
        "Laat de bovenste 3-5 cm opdrogen; ongeveer eens per 1-2 weken in de zomer, eens per 3 weken in de winter.",
        "Normale tot hogere luchtvochtigheid; bij droge lucht kan spint optreden.",
        "Ideaal 16-25°C; niet onder 10°C.",
        "Eens per maand in voorjaar en zomer met palmvoeding.",
        "Groeit langzaam en heeft een hekel aan verpotten; alleen om de 3-4 jaar, voorzichtig zonder de wortelkluit te breken.",
        "Bruine bladpunten = droge lucht of kalkrijk water; gele, afstervende onderste bladeren zijn natuurlijk.",
    ),
    "Parlor Palm": (
        "Verdraagt weinig licht; groeit het best in helder, indirect licht. Geen directe zon.",
        "Laat de bovenste 2-3 cm opdrogen; ongeveer eens per week in de zomer, minder in de winter.",
        "Houdt van gemiddelde tot hogere luchtvochtigheid; droge lucht geeft bruine punten en spint.",
        "Ideaal 18-25°C; niet onder 12°C.",
        "Eens per maand in voorjaar en zomer met palmvoeding op halve sterkte.",
        "Groeit langzaam; verpot om de 2-3 jaar in goed drainerende potgrond.",
        "Bruine bladpunten = droge lucht of hard water; gele bladeren = te nat.",
    ),
    "Areca Palm": (
        "Helder, indirect licht; verdraagt wat ochtendzon. Bij te weinig licht wordt hij ijl.",
        "Houd de grond licht vochtig; geef water zodra de bovenste 2-3 cm droog is. Gevoelig voor kalk - gebruik bij voorkeur regenwater.",
        "Houdt van 50%+ luchtvochtigheid; droge lucht geeft snel bruine bladpunten en spint.",
        "Ideaal 18-27°C; niet onder 15°C.",
        "Elke 2-4 weken in voorjaar en zomer met palmvoeding.",
        "Om de 2-3 jaar in goed drainerende potgrond.",
        "Bruine punten = droge lucht of hard water; gele bladeren kunnen wijzen op magnesium- of ijzergebrek.",
    ),
    "Lady Palm": (
        "Helder, indirect licht tot halfschaduw; geen directe zon.",
        "Laat de bovenste 3-5 cm opdrogen; ongeveer eens per 1-2 weken in de zomer.",
        "Normale kamerlucht is prima.",
        "Ideaal 15-25°C; verdraagt het koeler, tot ongeveer 7°C.",
        "Eens per maand in voorjaar en zomer met palmvoeding op halve sterkte.",
        "Groeit langzaam; verpot om de 3-4 jaar. Deel grote pollen bij het verpotten.",
        "Bruine bladpunten = droge lucht of te veel voeding; let op schildluis.",
    ),
    "Bamboo Palm": (
        "Helder, indirect licht; verdraagt minder licht.",
        "Houd de grond licht vochtig; geef water zodra de bovenste 2 cm droog is.",
        "Houdt van gemiddelde tot hogere luchtvochtigheid; droge lucht geeft spint.",
        "Ideaal 18-26°C; niet onder 12°C.",
        "Eens per maand in voorjaar en zomer met palmvoeding.",
        "Om de 2-3 jaar in goed drainerende potgrond.",
        "Bruine bladpunten = droge lucht of hard water; gespikkelde bladeren = spint.",
    ),
    "Poinsettia": (
        "Helder licht met wat ochtendzon. Na de feestdagen: zo licht mogelijk.",
        "Houd de grond licht vochtig; geef water zodra de bovenste 2 cm droog is. Nooit water in de schotel of hoes laten staan.",
        "Houdt van gemiddelde luchtvochtigheid.",
        "Ideaal 15-22°C; zeer gevoelig voor kou en tocht - al een korte rit in de kou bij aankoop kan bladval geven.",
        "Na de bloei elke 2-4 weken in voorjaar en zomer met kamerplantenvoeding; tijdens de bloei niet.",
        "Om opnieuw te laten kleuren: in het voorjaar terugsnoeien en verpotten, en vanaf eind september 8 weken lang elke nacht 14 uur volledig donker zetten. Het melksap irriteert de huid.",
        "Plotselinge bladval = kou, tocht of te nat. Gele bladeren onderaan = te nat.",
    ),
    "Christmas Cactus": (
        "Helder, indirect licht; geen felle zon. Het is een regenwoudcactus uit de schaduw van bomen.",
        "Houd de grond licht vochtig in groei en bloei (water zodra de bovenste 2 cm droog is). Na de bloei 6 weken rust met minder water.",
        "Houdt van gemiddelde tot hogere luchtvochtigheid.",
        "Ideaal 15-22°C. Koele nachten (12-15°C) in het najaar zetten de knopvorming in gang.",
        "Elke 2-4 weken in voorjaar en zomer met kamerplantenvoeding op halve sterkte; stoppen vanaf september.",
        "Om de 2-3 jaar na de bloei in luchtige grond (potgrond met orchideeënschors of perliet). Bloeit graag wat krap in de pot.",
        "Afvallende knoppen komen door verplaatsen, tocht of te warme lucht - draai de plant niet zodra hij knoppen heeft. Verschrompelde leden = te droog of wortelrot.",
    ),
    "Thanksgiving Cactus": (
        "Helder, indirect licht; geen felle middagzon.",
        "Houd de grond licht vochtig in groei en bloei; na de bloei een paar weken rust met minder water.",
        "Houdt van gemiddelde tot hogere luchtvochtigheid.",
        "Ideaal 15-22°C. Lange nachten en koele temperaturen (12-15°C) in oktober-november laten hem bloeien - meestal iets eerder dan de Kerstcactus.",
        "Elke 2-4 weken in voorjaar en zomer met kamerplantenvoeding op halve sterkte; stoppen vanaf september.",
        "Om de 2-3 jaar na de bloei in luchtige grond; bloeit graag wat krap in de pot. Stekken van 2-3 leden wortelen makkelijk.",
        "Knopval = verplaatsen of tocht; rode verkleuring van de leden = te veel zon of kou.",
    ),
    "Norfolk Island Pine": (
        "Veel helder licht; draai de pot elke week een kwartslag zodat de plant recht blijft groeien.",
        "Houd de grond licht vochtig; geef water zodra de bovenste 2-3 cm droog is.",
        "Houdt van hogere luchtvochtigheid; droge lucht geeft bruine, afvallende naalden.",
        "Houdt van koel tot gematigd: 10-21°C. Een koele, lichte winterplek is beter dan een warme woonkamer.",
        "Eens per maand in voorjaar en zomer met kamerplantenvoeding op halve sterkte.",
        "Om de 3-4 jaar in zure, goed drainerende potgrond. Nooit de top afknippen - de plant groeit dan niet meer in de hoogte.",
        "Bruine, afvallende onderste takken = te droge lucht, te droge grond of te weinig licht.",
    ),
    "Money Tree": (
        "Helder, indirect licht is ideaal, bijvoorbeeld een oost- of westraam; een beetje ochtendzon mag. Felle middagzon verbrandt de bladeren, en in een donkere hoek wordt de plant ijl en valt er blad af.",
        "Laat de bovenste 3-5 cm van de grond opdrogen en geef dan grondig water - in de zomer ongeveer eens per 7-10 dagen, in de winter eens per 2-3 weken. De dikke stam slaat water op, dus liever iets te weinig dan te veel. Gooi het water in de schotel na 15 minuten weg.",
        "Normale kamerlucht (40-60%) is prima; bij droge verwarmingslucht in de winter kun je de bladeren af en toe besproeien.",
        "Het prettigst tussen 18-25°C; niet onder 12°C. Houd de plant weg van tocht, radiatoren en koude ramen.",
        "Van april tot september elke 3-4 weken met kamerplantenvoeding op halve sterkte; in herfst en winter niet bemesten.",
        "Om de 2-3 jaar in het voorjaar, in een pot die maar iets groter is, met goed drainerende potgrond met extra perliet of zand. Laat de gevlochten stammen gevlochten; snoei te lange takken in het voorjaar terug voor een compacte kroon.",
        "Gele bladeren en een zachte, rimpelige stamvoet wijzen op te veel water (wortelrot); bruine bladranden op droge lucht of te veel zon; bladval na verplaatsen is een tijdelijke stressreactie. Let op spint en wolluis.",
    ),
    "Ficus Ginseng (Bonsai)": (
        "Veel helder licht met eventueel wat ochtendzon; een plek dicht bij het raam.",
        "Houd de grond licht vochtig; geef water zodra de bovenste cm droog is. In een ondiepe bonsaipot droogt de grond snel uit - controleer vaker.",
        "Houdt van gemiddelde tot hogere luchtvochtigheid; zet hem op een schaaltje met water en kiezels.",
        "Ideaal 16-24°C; niet onder 15°C en zonder tocht.",
        "Elke 2-4 weken in voorjaar en zomer met bonsaivoeding.",
        "Om de 2-3 jaar in het voorjaar in bonsaigrond; knip dan ook een deel van de wortels. Snoei nieuwe scheuten terug tot 2-3 bladeren voor een compacte vorm.",
        "Bladval = verplaatsing, tocht of te weinig licht; een zachte, rimpelige 'ginsengwortel' = te nat.",
    ),
    "Polka Dot Begonia": (
        "Helder, indirect licht; geen directe zon.",
        "Laat de bovenste 2 cm opdrogen; geef water op de grond, nooit over de bladeren. Nooit laten uitdrogen, maar ook nooit laten staan in water.",
        "Houdt van 50%+ luchtvochtigheid - maar niet besproeien, dat geeft meeldauw. Zet liever een schaaltje met water in de buurt.",
        "Ideaal 18-24°C; niet onder 15°C.",
        "Elke 2-4 weken in voorjaar en zomer met kamerplantenvoeding op halve sterkte.",
        "Om de 1-2 jaar in luchtige potgrond. Snoei de rietachtige stengels terug voor een volle plant; stekken wortelen makkelijk.",
        "Wit poeder op het blad = meeldauw (te vochtige, stilstaande lucht); bruine bladranden = droge lucht; zachte stengels = te nat.",
    ),
    "Rex Begonia Vine": (
        "Helder, indirect licht; geen directe zon.",
        "Houd de grond licht vochtig; laat de bovenste 2 cm opdrogen.",
        "Houdt van hogere luchtvochtigheid (60%+).",
        "Ideaal 18-26°C; niet onder 15°C.",
        "Elke 2-4 weken in voorjaar en zomer met kamerplantenvoeding op halve sterkte.",
        "Om de 1-2 jaar; geef een rek of steun om langs te klimmen of laat hem hangen.",
        "Bladval = te droge lucht of koud; vervaagde tekening = te weinig licht.",
    ),
    "Angel Wing Begonia": (
        "Helder, indirect licht; een paar uur ochtendzon bevordert de bloei.",
        "Laat de bovenste 2-3 cm opdrogen; giet op de grond, niet over het blad.",
        "Houdt van gemiddelde tot hogere luchtvochtigheid; niet besproeien (meeldauw).",
        "Ideaal 18-24°C; niet onder 13°C.",
        "Elke 2-4 weken in voorjaar en zomer met kamerplantenvoeding op halve sterkte.",
        "Om de 1-2 jaar in luchtige grond. Knip lange stengels in het voorjaar terug voor een vollere plant; geef hoge exemplaren een stok.",
        "Wit poeder = meeldauw; bladval en slappe stengels = te nat.",
    ),
    "Dumb Cane": (
        "Helder, indirect licht; verdraagt minder licht, maar dan wordt de plant lang en minder bont.",
        "Laat de bovenste 2-3 cm opdrogen; ongeveer eens per week in de zomer.",
        "Houdt van 50%+ luchtvochtigheid.",
        "Ideaal 18-26°C; niet onder 15°C.",
        "Elke 2-4 weken in voorjaar en zomer met kamerplantenvoeding.",
        "Om de 1-2 jaar in luchtige potgrond. Draag handschoenen bij snoeien of verpotten: het sap is giftig en irriteert mond en huid sterk.",
        "Gele onderste bladeren = natuurlijke veroudering of te nat; bruine randen = droge lucht.",
    ),
    "Silver Squill": (
        "Helder licht met wat zon voor de mooiste zilver- en paarse tekening.",
        "Laat de grond grotendeels opdrogen - de bolletjes slaan water op. In de winter nog minder water.",
        "Normale kamerlucht is prima.",
        "Ideaal 16-25°C; een koele winter (10-15°C) is prima.",
        "Eens per maand in voorjaar en zomer met kamerplantenvoeding op halve sterkte.",
        "Verpot zelden; bloeit het best als de bolletjes dicht op elkaar in een ondiepe pot staan. Zet de bollen half boven de grond.",
        "Zachte bolletjes = te nat; groene bladeren zonder tekening = te weinig licht.",
    ),
    "Coffee Plant": (
        "Helder, indirect licht; geen felle middagzon.",
        "Houd de grond gelijkmatig licht vochtig, maar niet nat. Gebruik bij voorkeur kalkarm water.",
        "Houdt van 50%+ luchtvochtigheid; besproei af en toe.",
        "Ideaal 18-24°C; niet onder 15°C.",
        "Elke 2-4 weken in voorjaar en zomer met kamerplantenvoeding (liefst voor zuurminnende planten).",
        "Om de 1-2 jaar in licht zure, humusrijke potgrond.",
        "Bruine bladranden = droge lucht of te droge grond; gele bladeren = kalk in het water of te nat.",
    ),
    "Bird's Nest Sansevieria": (
        "Helder licht tot halfschaduw; verdraagt weinig licht.",
        "Laat de grond volledig opdrogen - ongeveer eens per 2-3 weken in de zomer, eens per maand in de winter. Nooit water in de rozet.",
        "Droge lucht is prima.",
        "Ideaal 18-27°C; niet onder 10°C.",
        "Eens per maand in voorjaar en zomer met verdunde cactusvoeding.",
        "Blijft klein; verpot om de 2-3 jaar in een brede, ondiepe pot met cactusgrond.",
        "Rottende rozet = water in het hart of te nat.",
    ),
}
