"""Soortspecifieke Nederlandse verzorgingsgidsen - deel 3: orchideeën,
epifyten, vochtminnende planten, bromelia's en vleesetende planten.

Zelfde tuple-volgorde als part1.py: (licht, water geven,
luchtvochtigheid, temperatuur, bemesten, verpotten, problemen).
"""

GUIDES = {
    "Rattlesnake Plant Vine": (
        "Helder, indirect licht met wat ochtendzon; een oost- of westraam. Te weinig licht betekent geen of kleine bekers.",
        "Houd de grond altijd licht vochtig met regenwater of gedistilleerd water (geen kraanwater). Anders dan Sarracenia wil deze tropische bekerplant niet in een schotel water staan.",
        "Houdt van hoge luchtvochtigheid (60%+); zonder vochtige lucht maken nieuwe bladeren geen bekers.",
        "Ideaal 20-28°C; niet onder 15°C.",
        "Niet via de grond bemesten. Eventueel af en toe een insect in een beker, of een zeer verdunde orchideeënvoeding over het blad.",
        "Om de 2 jaar in een hangpot met luchtig, voedselarm mengsel (veenmos, perliet, orchideeënschors).",
        "Geen bekers = te droge lucht of te weinig licht; bruine bladpunten = kraanwater. Oude bekers die afsterven is normaal.",
    ),
    "Moth Orchid": (
        "Helder, indirect licht bij een oost- of noordraam; geen directe middagzon, dat geeft brandvlekken.",
        "Dompel de pot eens per 7-10 dagen 10 minuten in lauw (regen)water en laat daarna goed uitlekken. Zilvergrijze wortels = tijd voor water; groene wortels = nog vochtig. Nooit water in het hart van de bladrozet laten staan.",
        "Houdt van 50-60% luchtvochtigheid.",
        "Ideaal 18-27°C. Een paar weken koelere nachten (ongeveer 16°C) in het najaar stimuleert een nieuwe bloeitak.",
        "Elke 2-3 weken een kwart- tot halve dosis orchideeënvoeding in het dompelwater.",
        "Om de 2 jaar na de bloei in verse orchideeënschors, in een doorzichtige pot met veel gaten. Knip dode, holle wortels weg.",
        "Knopval = tocht, verplaatsen of te droge lucht. Hart- of kroonrot = water in de rozet. Knip een uitgebloeide tak af boven het tweede 'oogje' voor een zijtak met nieuwe bloemen.",
    ),
    "Dendrobium Orchid": (
        "Veel helder licht met wat ochtendzon; meer licht dan een Phalaenopsis.",
        "In de groeiperiode (voorjaar-zomer) eens per week dompelen of grondig water geven; laat daarna uitlekken. Na de groei in de herfst een drogere rustperiode.",
        "Houdt van 50-60% luchtvochtigheid.",
        "Ideaal 18-27°C overdag; koele nachten (10-15°C) in de herfst zijn nodig voor bloemknoppen.",
        "Elke 2 weken in de groeiperiode met orchideeënvoeding op halve sterkte; stoppen in de rustperiode.",
        "Om de 2-3 jaar na de bloei in grove orchideeënschors, in een kleine pot.",
        "Geen bloei = geen koele, droge rustperiode; kleine plantjes (keiki's) op de stengels in plaats van bloemen = te veel water of voeding in de rust.",
    ),
    "Cattleya Orchid": (
        "Veel licht met een paar uur ochtendzon; lichtgroen blad is goed, donkergroen betekent te weinig licht.",
        "Laat de schors bijna droog worden en geef dan grondig water; ongeveer eens per week in de zomer, eens per 2 weken in de winter.",
        "Houdt van 50-70% luchtvochtigheid met goede luchtcirculatie.",
        "Ideaal 18-29°C overdag met nachten zo'n 5°C koeler.",
        "Elke 2 weken in de groeiperiode met orchideeënvoeding op halve sterkte.",
        "Verpot om de 2-3 jaar, als de nieuwe scheut begint te wortelen, in grove schors.",
        "Geen bloei = te weinig licht; gerimpelde pseudobulben = te droog of wortelrot.",
    ),
    "Oncidium Orchid": (
        "Helder, indirect licht met wat ochtendzon.",
        "Houd de schors licht vochtig in de groeiperiode (ongeveer eens per week dompelen); de dunne wortels drogen snel uit.",
        "Houdt van 50-60% luchtvochtigheid.",
        "Ideaal 16-26°C; iets koelere nachten stimuleren bloei.",
        "Elke 2 weken in de groeiperiode met orchideeënvoeding op halve sterkte.",
        "Om de 2 jaar in fijne orchideeënschors, net na de bloei of als nieuwe groei begint.",
        "Harmonica-achtig geplooide nieuwe bladeren = te droog of te droge lucht; gerimpelde pseudobulben = te weinig water.",
    ),
    "Staghorn Fern": (
        "Helder, indirect licht; geen directe zon.",
        "Dompel de plank of pot eens per week (in de zomer) 10-15 minuten in lauw water; in de winter eens per 2-3 weken. De bruine schildbladen aan de voet horen zo - niet weghalen.",
        "Houdt van 50%+ luchtvochtigheid; een lichte badkamer is ideaal.",
        "Ideaal 16-26°C; niet onder 10°C.",
        "Eens per maand in de groeiperiode met verdunde (orchideeën)voeding in het dompelwater.",
        "Wordt vaak op een plank met veenmos gemonteerd; groeit hij over de rand, monteer hem dan op een grotere plank.",
        "Zwarte plekken aan de voet = te nat; bruine, verdroogde 'geweien' = te droog of te droge lucht. Het zilverachtige poeder op het blad is normaal - niet afvegen.",
    ),
    "Peace Lily": (
        "Verdraagt weinig licht, maar bloeit alleen in helder, indirect licht. Geen directe zon.",
        "Houd de grond licht vochtig; laat de bovenste 2 cm opdrogen. Hangende bladeren betekenen dorst - de plant herstelt binnen een paar uur na water, maar laat dit niet te vaak gebeuren.",
        "Houdt van 50%+ luchtvochtigheid; besproei af en toe.",
        "Ideaal 18-26°C; niet onder 15°C.",
        "Elke 2-4 weken in voorjaar en zomer met kamerplantenvoeding op halve sterkte.",
        "Om de 1-2 jaar in het voorjaar in humusrijke potgrond. Deel grote pollen bij het verpotten.",
        "Bruine bladpunten = kalkrijk water of droge lucht; geen bloei = te weinig licht; gele bladeren = te nat of te veel voeding.",
    ),
    "Prayer Plant": (
        "Helder tot matig indirect licht; directe zon laat de tekening vervagen.",
        "Houd de grond licht vochtig met kalkarm water op kamertemperatuur; laat hem nooit uitdrogen.",
        "Houdt van 60%+ luchtvochtigheid; een luchtbevochtiger of lichte badkamer helpt enorm.",
        "Ideaal 18-26°C; niet onder 15°C.",
        "Elke 2-4 weken in voorjaar en zomer met kamerplantenvoeding op halve sterkte.",
        "Om de 1-2 jaar in het voorjaar in een brede, ondiepe pot met luchtige potgrond.",
        "Krullende bladeren en bruine randen = droge lucht of te droge grond; vervaagde kleuren = te veel licht.",
    ),
    "Rattlesnake Plant": (
        "Helder tot matig indirect licht; geen directe zon.",
        "Houd de grond licht vochtig met regenwater of gefilterd water; gevoelig voor kalk en fluoride.",
        "Houdt van 60%+ luchtvochtigheid.",
        "Ideaal 18-26°C; niet onder 16°C.",
        "Elke 3-4 weken in voorjaar en zomer met kamerplantenvoeding op halve sterkte.",
        "Om de 1-2 jaar in luchtige, vochtvasthoudende potgrond.",
        "Oprollende bladeren = te droog of te droge lucht; bruine randen = kraanwater of droge lucht. Let op spint.",
    ),
    "Peacock Plant": (
        "Matig tot helder indirect licht; directe zon verbleekt de tekening.",
        "Houd de grond licht vochtig met kalkarm water (regenwater). Nooit laten uitdrogen.",
        "Houdt van 60%+ luchtvochtigheid.",
        "Ideaal 18-26°C; niet onder 16°C.",
        "Elke 3-4 weken in voorjaar en zomer met kamerplantenvoeding op halve sterkte.",
        "Om de 1-2 jaar in luchtige potgrond.",
        "Bruine bladranden = droge lucht of kraanwater; krullende bladeren = te droog.",
    ),
    "Calathea Medallion": (
        "Helder tot matig indirect licht; geen directe zon.",
        "Houd de grond licht vochtig met regenwater of gefilterd water.",
        "Houdt van 60%+ luchtvochtigheid.",
        "Ideaal 18-26°C; niet onder 16°C en zonder tocht.",
        "Elke 3-4 weken in voorjaar en zomer met kamerplantenvoeding op halve sterkte.",
        "Om de 1-2 jaar in luchtige, vochtvasthoudende potgrond.",
        "Bruine, knisperende randen = droge lucht of kraanwater; gele bladeren = te nat.",
    ),
    "Calathea Orbifolia": (
        "Helder, indirect licht; directe zon verbrandt de grote bladeren.",
        "Houd de grond gelijkmatig licht vochtig met regenwater of gefilterd water; een van de gevoeligste Calathea's voor uitdrogen.",
        "Houdt van 60-70% luchtvochtigheid; een luchtbevochtiger is eigenlijk onmisbaar.",
        "Ideaal 18-26°C; niet onder 16°C.",
        "Elke 3-4 weken in voorjaar en zomer met kamerplantenvoeding op halve sterkte.",
        "Om de 1-2 jaar in het voorjaar in luchtige potgrond.",
        "Bruine bladranden en krullende bladeren = droge lucht; gele onderste bladeren = te nat. Let op spint.",
    ),
    "Fishbone Prayer Plant": (
        "Helder tot matig indirect licht.",
        "Houd de grond licht vochtig met kalkarm water.",
        "Houdt van 60%+ luchtvochtigheid.",
        "Ideaal 18-26°C; niet onder 15°C.",
        "Elke 3-4 weken in voorjaar en zomer met kamerplantenvoeding op halve sterkte.",
        "Om de 1-2 jaar in luchtige potgrond.",
        "Oprollende bladeren = te droog; bruine randen = droge lucht of kraanwater.",
    ),
    "Never-Never Plant": (
        "Helder, indirect licht voor de bonte tekening.",
        "Houd de grond licht vochtig met kalkarm water.",
        "Houdt van 60%+ luchtvochtigheid.",
        "Ideaal 18-26°C; niet onder 15°C.",
        "Elke 3-4 weken in voorjaar en zomer met kamerplantenvoeding op halve sterkte.",
        "Om de 1-2 jaar; deel grote pollen bij het verpotten.",
        "Bruine randen = droge lucht; oprollende bladeren = te droog.",
    ),
    "Nerve Plant": (
        "Matig tot helder indirect licht; directe zon verbrandt de dunne bladeren.",
        "Houd de grond altijd licht vochtig; hij hangt dramatisch als hij dorst heeft. Herstelt meestal snel, maar herhaald uitdrogen verzwakt hem.",
        "Houdt van 60%+ luchtvochtigheid; ideaal voor een terrarium of flessentuin.",
        "Ideaal 18-26°C; niet onder 15°C.",
        "Eens per maand in voorjaar en zomer met kamerplantenvoeding op kwart sterkte.",
        "Om de 1-2 jaar; top de scheuten regelmatig voor een compacte plant.",
        "Bruine, verschrompelde bladeren = droge lucht; slappe, zwarte stengels = te nat.",
    ),
    "African Mask Plant": (
        "Helder, indirect licht; geen directe zon.",
        "Laat de bovenste 2-3 cm opdrogen en geef dan water; houd de grond verder licht vochtig. Gevoelig voor te nat én te droog.",
        "Houdt van 60%+ luchtvochtigheid.",
        "Ideaal 18-27°C; niet onder 15°C.",
        "Elke 2-4 weken in voorjaar en zomer met kamerplantenvoeding op halve sterkte.",
        "Om de 1-2 jaar in het voorjaar in luchtige aroidenmix.",
        "Bladeren die in de winter afsterven kan rust zijn - de knol loopt weer uit. Gespikkelde bladeren = spint (bekend probleem bij Alocasia).",
    ),
    "Elephant Ear": (
        "Helder licht met wat directe ochtendzon.",
        "Een echte waterdrinker: houd de grond constant vochtig in het groeiseizoen. In de winter minder.",
        "Houdt van 60%+ luchtvochtigheid.",
        "Ideaal 20-29°C; niet onder 15°C.",
        "Elke 2 weken in voorjaar en zomer met kamerplantenvoeding.",
        "Om de 1-2 jaar in voedzame, vochtvasthoudende potgrond in een grote pot.",
        "Hangende bladeren = te droog; bladeren die afsterven in de winter = rust.",
    ),
    "Flamingo Flower": (
        "Helder, indirect licht voor een lange bloei; geen directe zon.",
        "Laat de bovenste 2-3 cm opdrogen; ongeveer eens per week. Gebruik bij voorkeur kalkarm water op kamertemperatuur.",
        "Houdt van 60%+ luchtvochtigheid.",
        "Ideaal 18-27°C; niet onder 16°C.",
        "Elke 2-4 weken in voorjaar en zomer met fosforrijke (bloei)voeding op halve sterkte.",
        "Om de 2 jaar in het voorjaar in grove, luchtige mix (potgrond met orchideeënschors en perliet).",
        "Geen bloei = te weinig licht; gele bladeren = te nat; bruine bladpunten = droge lucht.",
    ),
    "Rex Begonia": (
        "Helder, indirect licht; directe zon verbrandt het blad.",
        "Laat de bovenste 2 cm opdrogen; geef water op de grond, nooit over het blad.",
        "Houdt van 50%+ luchtvochtigheid - niet besproeien (meeldauw); gebruik een schaaltje met water.",
        "Ideaal 18-24°C; niet onder 15°C.",
        "Elke 2-4 weken in voorjaar en zomer met kamerplantenvoeding op halve sterkte.",
        "Om de 1-2 jaar in een ondiepe pot met luchtige potgrond. Een bladstek wortelt op vochtige grond.",
        "Wit poeder = meeldauw; zachte stengels = te nat; bruine bladranden = droge lucht.",
    ),
    "Boston Fern": (
        "Helder, indirect licht; geen directe zon.",
        "Houd de grond constant licht vochtig; laat hem nooit uitdrogen.",
        "Houdt van 60%+ luchtvochtigheid; besproei dagelijks of zet hem in een lichte badkamer.",
        "Ideaal 16-24°C; een koelere kamer is beter dan een warme.",
        "Eens per maand in voorjaar en zomer met kamerplantenvoeding op halve sterkte.",
        "Om de 1-2 jaar in het voorjaar; deel grote planten.",
        "Bruine, afvallende blaadjes = droge lucht of te droge grond - het meest voorkomende probleem.",
    ),
    "Maidenhair Fern": (
        "Helder, indirect licht; geen directe zon.",
        "Houd de grond altijd licht vochtig met kalkarm water; één keer uitdrogen kan al veel blad kosten.",
        "Houdt van 60%+ luchtvochtigheid; ideaal voor een badkamer of terrarium.",
        "Ideaal 16-24°C; zonder tocht.",
        "Eens per maand in voorjaar en zomer met kamerplantenvoeding op kwart sterkte.",
        "Om de 1-2 jaar in het voorjaar. Knip verdroogde bladeren bij de grond af - de plant loopt vaak weer uit.",
        "Verschrompelde, bruine blaadjes = te droog of te droge lucht.",
    ),
    "Bird's Nest Fern": (
        "Helder tot matig indirect licht; geen directe zon.",
        "Laat de bovenste 2-3 cm opdrogen en geef water aan de rand van de pot - niet in het hart van de rozet (rotgevaar).",
        "Houdt van 50%+ luchtvochtigheid.",
        "Ideaal 18-24°C; niet onder 15°C.",
        "Eens per maand in voorjaar en zomer met kamerplantenvoeding op halve sterkte.",
        "Om de 2 jaar in het voorjaar in luchtige grond met schors of veenmos.",
        "Bruine bladranden = droge lucht; bruin rottend hart = water in de rozet. Raak de jonge, opkrullende bladeren niet aan.",
    ),
    "Table Fern": (
        "Helder, indirect licht; bonte vormen willen meer licht.",
        "Houd de grond licht vochtig.",
        "Houdt van 50%+ luchtvochtigheid.",
        "Ideaal 15-22°C; verdraagt het koeler dan veel varens.",
        "Eens per maand in voorjaar en zomer met kamerplantenvoeding op halve sterkte.",
        "Om de 1-2 jaar in het voorjaar.",
        "Bruine blaadjes = te droog of droge lucht.",
    ),
    "Baby's Tears": (
        "Helder, indirect licht; geen directe zon.",
        "Houd de grond constant vochtig; geef water van onderaf.",
        "Houdt van hoge luchtvochtigheid; ideaal voor terraria.",
        "Houdt van koel: 10-20°C.",
        "Eens per maand in voorjaar en zomer met kamerplantenvoeding op kwart sterkte.",
        "Groeit snel; deel en verpot wanneer nodig.",
        "Verdroogde, bruine plekken = te droog; rotte plekken = te nat en te warm.",
    ),
    "Spikemoss": (
        "Matig indirect licht; geen directe zon.",
        "Houd de grond constant vochtig.",
        "Heeft zeer hoge luchtvochtigheid nodig (70%+); een terrarium is ideaal.",
        "Ideaal 16-24°C.",
        "Nauwelijks nodig; hooguit eens per 2 maanden zeer verdunde voeding.",
        "Verpot zelden; deel de mat wanneer nodig.",
        "Bruine, droge plekken = te droge lucht.",
    ),
    "African Violet": (
        "Helder, indirect licht bij een oost- of noordraam; geen directe zon.",
        "Geef water van onderaf: zet de pot 20 minuten in lauw water en laat uitlekken. Laat de bovenste cm opdrogen voor de volgende beurt. Nooit koud water op de bladeren - dat geeft lichte vlekken.",
        "Houdt van 50%+ luchtvochtigheid, maar niet besproeien.",
        "Ideaal 18-24°C; niet onder 16°C.",
        "Elke 2-3 weken met speciale Saintpaulia-/bloeivoeding op halve sterkte.",
        "Bloeit graag in een kleine pot; verpot eens per jaar in speciale Saintpaulia-grond.",
        "Lichte vlekken op het blad = koud water; geen bloei = te weinig licht; rot in het hart = te nat.",
    ),
    "Cape Primrose": (
        "Helder, indirect licht; geen directe middagzon.",
        "Laat de bovenste 2 cm opdrogen; geef water op de grond, niet op de bladeren.",
        "Houdt van gemiddelde luchtvochtigheid.",
        "Ideaal 16-24°C.",
        "Elke 2 weken tijdens de bloei met bloeivoeding op halve sterkte.",
        "Bloeit graag krap; verpot in een ondiepe pot in het voorjaar.",
        "Verdroogde bladpunten zijn normaal - knip ze af. Zachte bladvoeten = te nat.",
    ),
    "Cyclamen": (
        "Helder, indirect licht; geen directe zon.",
        "Geef water van onderaf (schotel 20 minuten, daarna leeggieten); nooit water op de knol. Laat de bovenste 2 cm opdrogen. In de zomerrust veel minder water.",
        "Normale tot hogere luchtvochtigheid.",
        "Houdt van koel: 10-18°C. In een warme woonkamer is de bloei snel voorbij; een koele vensterbank is ideaal.",
        "Elke 2 weken tijdens de bloei met bloeivoeding op halve sterkte.",
        "Na de bloei gaat de plant in rust; zet de knol in de herfst in verse grond met de bovenkant boven de grond.",
        "Gele bladeren = te warm of te nat; rottende knol = water op de knol gegoten.",
    ),
    "Primrose": (
        "Helder licht met wat zon.",
        "Houd de grond licht vochtig.",
        "Normale kamerlucht.",
        "Houdt van koel: 10-16°C. In een warme kamer is de bloei kort.",
        "Elke 2 weken tijdens de bloei met bloeivoeding op halve sterkte.",
        "Na de bloei kun je hem in de tuin zetten; hij is winterhard.",
        "Snel verwelkende bloemen = te warm; gele bladeren = te nat.",
    ),
    "Caladium": (
        "Helder, indirect licht; directe zon verbrandt de dunne bladeren.",
        "Houd de grond licht vochtig in het groeiseizoen; zodra de bladeren in de herfst afsterven, de knol droog houden.",
        "Houdt van 60%+ luchtvochtigheid.",
        "Ideaal 21-29°C; niet onder 16°C.",
        "Elke 2-4 weken in voorjaar en zomer met kamerplantenvoeding op halve sterkte.",
        "Bewaar de knol in de winter droog bij 15-18°C en plant hem in het voorjaar opnieuw.",
        "Bladeren die in de herfst afsterven = normale rust. Rottende knol = te koud en te nat.",
    ),
    "Guzmania Bromeliad": (
        "Helder, indirect licht; geen directe zon.",
        "Houd de centrale koker (beker) een laagje water gevuld en ververs het elke 1-2 weken. De grond zelf alleen licht vochtig houden.",
        "Houdt van 50%+ luchtvochtigheid.",
        "Ideaal 18-27°C; niet onder 15°C.",
        "Eens per maand een zeer verdunde voeding in de koker of over het blad.",
        "De moederplant bloeit één keer en sterft daarna langzaam af. Zet de jonge scheuten (kindjes) apart als ze ongeveer een derde van de moederplant groot zijn.",
        "Een bruin wordende bloem na maanden is normaal. Rot in de koker = stilstaand water niet ververst.",
    ),
    "Vriesea Bromeliad": (
        "Helder, indirect licht.",
        "Houd de koker een laagje water gevuld (liefst regenwater) en ververs het elke 1-2 weken; de grond licht vochtig houden.",
        "Houdt van 50%+ luchtvochtigheid.",
        "Ideaal 18-27°C; niet onder 15°C.",
        "Eens per maand een zeer verdunde voeding in de koker.",
        "Na de bloei de kindjes apart zetten zodra ze groot genoeg zijn.",
        "Bruine bladpunten = kalkrijk water of droge lucht.",
    ),
    "Aechmea Bromeliad": (
        "Helder licht met wat ochtendzon; verdraagt meer licht dan Guzmania.",
        "Houd de koker een laagje water gevuld en ververs het regelmatig; de grond licht vochtig.",
        "Normale tot hogere luchtvochtigheid.",
        "Ideaal 18-27°C.",
        "Eens per maand een zeer verdunde voeding in de koker.",
        "Na de bloei (die maanden kan duren) de kindjes apart zetten.",
        "Rot aan de voet = te natte grond; vlekken op het blad = te felle zon.",
    ),
    "Azalea (potted)": (
        "Helder licht zonder directe middagzon.",
        "Houd de wortelkluit altijd vochtig met kalkarm water (regenwater); dompel de pot eens per week. Uitdrogen geeft direct bladval.",
        "Houdt van hogere luchtvochtigheid.",
        "Houdt van koel: 10-18°C. Hoe koeler, hoe langer de bloei.",
        "Na de bloei elke 2 weken met voeding voor zuurminnende planten (rododendronvoeding).",
        "Na de bloei in zure rododendrongrond; kan 's zomers buiten in de halfschaduw staan.",
        "Bladval en verdroogde bloemen = te droog of te warm; gele bladeren met groene nerven = kalk in het water.",
    ),
    "Hydrangea (potted)": (
        "Helder licht zonder felle middagzon.",
        "Een echte waterdrinker: houd de grond constant vochtig, in de bloei vaak dagelijks. Gebruik bij voorkeur regenwater.",
        "Normale kamerlucht.",
        "Houdt van koel: 12-18°C.",
        "Elke 2 weken in voorjaar en zomer met hortensiavoeding.",
        "Na de bloei in de tuin of een grote pot buiten zetten; de meeste zijn winterhard.",
        "Slap hangen = dorst; bruine bloemen = te warm of te droog.",
    ),
    "Umbrella Papyrus": (
        "Helder licht met wat zon.",
        "Een moerasplant: laat de pot altijd in een schotel met een paar cm water staan.",
        "Houdt van hogere luchtvochtigheid.",
        "Ideaal 16-24°C.",
        "Elke 2 weken in voorjaar en zomer met kamerplantenvoeding.",
        "Om de 1-2 jaar; deel grote pollen.",
        "Bruine bladpunten = droge lucht of een schotel die droog is gevallen.",
    ),
    "Venus Flytrap": (
        "Zoveel mogelijk licht met directe zon - minstens 4 uur per dag; een zuidraam of 's zomers buiten.",
        "Zet de pot in een schotel met een laagje regenwater of gedistilleerd water. Nooit kraanwater: de mineralen doden de plant.",
        "Normale kamerlucht is prima.",
        "Zomer 20-30°C. Heeft een koude winterrust nodig (0-10°C) van november tot februari, anders put hij uit.",
        "Nooit bemesten via de grond. Hij vangt zelf insecten; voer hem niet met vlees en laat de vallen niet 'voor de lol' dichtklappen.",
        "Verpot elk voorjaar in een voedselarm mengsel van turf/veenmos en perliet; nooit gewone potgrond.",
        "Zwarte vallen zijn normaal na het verteren of na een paar keer dichtklappen. Een hele plant die zwart wordt = kraanwater, bemesting of te weinig licht.",
    ),
    "Pitcher Plant": (
        "Zoveel mogelijk directe zon; zonder volle zon blijven de bekers klein en groen.",
        "Zet de pot in een schotel met een paar cm regenwater of gedistilleerd water; nooit kraanwater.",
        "Normale kamerlucht is prima.",
        "Zomer 20-30°C; heeft een koude winterrust (0-10°C) nodig en doet het het best buiten op balkon of terras.",
        "Nooit bemesten; hij vangt zelf insecten.",
        "Verpot in het voorjaar in voedselarm turf/veenmos met perliet.",
        "Bruine bekers in de herfst zijn normaal - knip ze in het voorjaar af. Slappe, groene bekers = te weinig licht.",
    ),
    "Sundew": (
        "Veel licht met directe zon; het plakkerige 'dauw' verschijnt pas bij genoeg licht.",
        "Zet de pot in een schotel met een laagje regenwater of gedistilleerd water.",
        "Houdt van hogere luchtvochtigheid.",
        "Ideaal 15-28°C; Drosera capensis heeft geen koude winterrust nodig.",
        "Niet bemesten; hij vangt zelf fruitvliegjes en rouwmuggen.",
        "Verpot in het voorjaar in voedselarm turf/veenmos met perliet. Zaait zichzelf makkelijk uit.",
        "Geen dauw op de tentakels = te droge lucht of te weinig licht.",
    ),
    "Calla Lily (potted)": (
        "Helder licht met wat zon.",
        "Houd de grond tijdens groei en bloei constant vochtig. Na de bloei geleidelijk minder water; laat de knol daarna een paar maanden rusten.",
        "Normale kamerlucht.",
        "Ideaal 16-22°C tijdens de bloei.",
        "Elke 2 weken tijdens groei en bloei met bloeivoeding.",
        "Plant de knol in het voorjaar opnieuw in verse potgrond.",
        "Geen bloei = te weinig licht of geen rustperiode; gele bladeren na de bloei = normaal.",
    ),
    "Sensitive Plant": (
        "Veel helder licht met wat directe zon.",
        "Houd de grond licht vochtig; nooit laten uitdrogen.",
        "Houdt van hogere luchtvochtigheid.",
        "Ideaal 18-28°C; niet onder 15°C.",
        "Elke 2-4 weken in voorjaar en zomer met kamerplantenvoeding op halve sterkte.",
        "Wordt vaak als eenjarige gekweekt; eenvoudig uit zaad op te kweken.",
        "Blaadjes die niet meer opengaan = te vaak aangeraakt of te weinig licht. Raak ze niet te vaak aan: het kost de plant energie.",
    ),
}
