"""Soortspecifieke Nederlandse verzorgingsgidsen - deel 4: overige
vetplanten, aroiden, peperomia's, bloeiende planten, palmen en de
aanvullingen uit het Nederlandse tuincentrum-assortiment.

Zelfde tuple-volgorde als part1.py: (licht, water geven,
luchtvochtigheid, temperatuur, bemesten, verpotten, problemen).
"""

GUIDES = {
    "Mexican Snowball": (
        "Veel licht met directe zon; de blauwgrijze rozetten blijven dan compact en krijgen roze randjes.",
        "Laat de grond volledig opdrogen; ongeveer eens per 2 weken in de zomer, eens per maand in de winter. Nooit water in de rozet.",
        "Droge lucht is prima; niet besproeien.",
        "Ideaal 15-26°C; een koele, droge winter (8-12°C) is gezond.",
        "Eens per maand in voorjaar en zomer met verdunde cactusvoeding.",
        "Om de 2 jaar in een ondiepe pot met cactusgrond; uitlopers makkelijk los te maken.",
        "Uitgerekte rozetten met ver uit elkaar staande bladeren = te weinig licht; zachte, doorschijnende bladeren = te nat.",
    ),
    "Echeveria 'Perle von Nurnberg'": (
        "Veel licht met directe zon voor de paars-roze kleur.",
        "Laat de grond volledig opdrogen; ongeveer eens per 2 weken in de zomer. Giet op de grond, niet over de bepoederde bladeren.",
        "Droge lucht is prima.",
        "Ideaal 15-26°C; niet onder 5°C.",
        "Eens per maand in voorjaar en zomer met verdunde cactusvoeding.",
        "Om de 2 jaar in cactusgrond. Verdroogde onderste bladeren kun je voorzichtig weghalen.",
        "Verbleken naar grijsgroen = te weinig licht; zachte bladeren = te nat. Raak de waslaag niet aan.",
    ),
    "Tree Houseleek": (
        "Veel licht met directe zon; zwartbladige vormen ('Zwartkop') kleuren alleen bij veel zon.",
        "Groeit vooral in de koele maanden: geef in herfst tot voorjaar water als de grond droog is. In de zomer gaat hij deels in rust - dan minder water; de rozetten sluiten zich.",
        "Droge lucht is prima.",
        "Ideaal 10-24°C; houdt niet van hitte boven 30°C.",
        "Eens per maand tijdens de groei met verdunde cactusvoeding.",
        "Om de 2 jaar in cactusgrond met wat potgrond. Kopstekken wortelen makkelijk.",
        "Gesloten, kleiner wordende rozetten in de zomer = normale rust. Een rozet die na de bloei afsterft is normaal.",
    ),
    "Mother of Thousands": (
        "Veel licht met wat directe zon.",
        "Laat de grond grotendeels opdrogen; ongeveer eens per 2 weken.",
        "Droge lucht is prima.",
        "Ideaal 16-26°C; niet onder 10°C.",
        "Eens per maand in voorjaar en zomer met verdunde cactusvoeding.",
        "Om de 2 jaar in cactusgrond. De plantjes langs de bladrand vallen overal in andere potten - houd hem apart of verwijder ze regelmatig.",
        "Lange, kale stengel = normaal bij oudere planten; knip de top af en stek opnieuw.",
    ),
    "Watch Chain Plant": (
        "Veel licht met wat directe zon.",
        "Laat de grond helemaal opdrogen; eens per 2-3 weken. Giet op de grond.",
        "Droge lucht is prima.",
        "Ideaal 15-25°C; een koele winter is goed.",
        "Eens per maand in voorjaar en zomer met verdunde cactusvoeding.",
        "Om de 2 jaar in cactusgrond. Afgebroken takjes wortelen makkelijk.",
        "Bruin wordende, droge onderste blaadjes zijn normaal; zwarte, zachte stengels = te nat.",
    ),
    "Fairy Washboard": (
        "Helder, indirect licht of zachte ochtendzon.",
        "Laat de grond volledig opdrogen; eens per 2-3 weken in de zomer, eens per maand in de winter.",
        "Droge lucht is prima.",
        "Ideaal 18-25°C; niet onder 10°C.",
        "Eens per maand in voorjaar en zomer met verdunde cactusvoeding.",
        "Om de 2-3 jaar in cactusgrond.",
        "Rood-bruine verkleuring = te veel zon; zachte bladeren = te nat.",
    ),
    "Baseball Plant": (
        "Veel licht met directe zon.",
        "Laat de grond volledig opdrogen; eens per 2-3 weken in de zomer, in de winter vrijwel droog.",
        "Droge lucht is prima.",
        "Ideaal 18-28°C; winterrust bij 10-15°C.",
        "Eens per maand in voorjaar en zomer met verdunde cactusvoeding.",
        "Verpot zelden, in zeer goed drainerende cactusgrond. Het melksap irriteert.",
        "Een ingezakte, zachte bal = rot door te veel water.",
    ),
    "Living Stones": (
        "Zoveel mogelijk directe zon; een zuidraam.",
        "Het lastigste punt: geef alleen water in de groeiperiode (meestal eind zomer-herfst) als de grond droog is. Tijdens de bladwisseling (winter-voorjaar) helemaal géén water - de nieuwe bladeren leven van het oude bladpaar.",
        "Droge lucht is ideaal.",
        "Ideaal 15-28°C; in de winter koel en droog.",
        "Nauwelijks nodig; hooguit één keer per jaar een zeer verdunde cactusvoeding.",
        "Verpot zelden, in puur mineraal substraat (grit, puimsteen) in een diepe pot voor de penwortel.",
        "Gebarsten of opgezwollen bladeren = te veel water; nieuwe bladeren die bovenop het oude paar verschijnen zonder dat dat verschrompelt = te veel water tijdens de wissel.",
    ),
    "Jelly Bean Plant": (
        "Veel licht met directe zon; de 'boontjes' kleuren dan knalrood.",
        "Laat de grond volledig opdrogen; eens per 2 weken in de zomer.",
        "Droge lucht is prima.",
        "Ideaal 15-26°C.",
        "Eens per maand in voorjaar en zomer met verdunde cactusvoeding.",
        "Om de 2 jaar in cactusgrond; afgevallen blaadjes wortelen makkelijk.",
        "Groen blijven = te weinig zon; zachte, doorschijnende boontjes = te nat.",
    ),
    "Starfish Flower": (
        "Veel licht met directe zon.",
        "Laat de grond volledig opdrogen; in de zomer eens per 2 weken, in de winter vrijwel droog.",
        "Droge lucht is prima.",
        "Ideaal 18-28°C; winterrust bij 10-15°C.",
        "Eens per maand in voorjaar en zomer met verdunde cactusvoeding.",
        "Om de 2 jaar in cactusgrond.",
        "De grote stervormige bloemen ruiken naar aas om vliegen te lokken - dat is normaal. Zachte stengels = te nat.",
    ),
    "Hoya Bella": (
        "Helder licht met wat ochtendzon; zonder genoeg licht geen bloei.",
        "Laat de bovenste helft van de grond opdrogen - iets dorstiger dan andere Hoya's. Ongeveer eens per week in de zomer.",
        "Houdt van hogere luchtvochtigheid.",
        "Ideaal 18-25°C; niet onder 15°C.",
        "Elke 2-4 weken in voorjaar en zomer met bloeivoeding op halve sterkte.",
        "Bloeit het best krap in de pot; verpot zelden, in luchtige mix met schors en perliet.",
        "Knip de bloemsteeltjes niet af; verplaats de plant niet met knoppen. Let op wolluis.",
    ),
    "Neon Pothos": (
        "Helder, indirect licht voor de knalgroene kleur; bij weinig licht wordt het blad donkerder.",
        "Laat de bovenste helft van de grond opdrogen; ongeveer eens per week in de zomer.",
        "Normale kamerlucht is prima.",
        "Ideaal 18-27°C; niet onder 15°C.",
        "Elke 2-4 weken in voorjaar en zomer met kamerplantenvoeding op halve sterkte.",
        "Om de 1-2 jaar in gewone kamerplantengrond. Stekken wortelen makkelijk in water.",
        "Bruine vlekken = te veel directe zon; gele bladeren = te nat.",
    ),
    "Cebu Blue Pothos": (
        "Helder, indirect licht; verdraagt wat ochtendzon.",
        "Laat de bovenste helft van de grond opdrogen; ongeveer eens per week.",
        "Houdt van iets hogere luchtvochtigheid.",
        "Ideaal 18-27°C.",
        "Elke 2-4 weken in voorjaar en zomer met kamerplantenvoeding.",
        "Om de 1-2 jaar in luchtige aroidenmix. Aan een mosstok worden de bladeren groter en krijgen ze insnijdingen.",
        "Gele bladeren = te nat; kleine bladeren = te weinig licht of geen klimsteun.",
    ),
    "Philodendron Prince of Orange": (
        "Helder, indirect licht voor de oranje nieuwe bladeren.",
        "Laat de bovenste 2-3 cm opdrogen; ongeveer eens per week.",
        "Houdt van 50%+ luchtvochtigheid.",
        "Ideaal 18-27°C; niet onder 15°C.",
        "Elke 3-4 weken in voorjaar en zomer met kamerplantenvoeding.",
        "Om de 2 jaar in luchtige aroidenmix. Groeit compact, niet klimmend.",
        "Dof oranje of groene nieuwe bladeren = te weinig licht; gele oude bladeren = te nat.",
    ),
    "Philodendron Congo": (
        "Helder tot matig indirect licht.",
        "Laat de bovenste 3-5 cm opdrogen; ongeveer eens per week.",
        "Normale tot hogere luchtvochtigheid.",
        "Ideaal 18-27°C.",
        "Elke 3-4 weken in voorjaar en zomer met kamerplantenvoeding.",
        "Om de 2 jaar in een brede pot met luchtige potgrond.",
        "Gele bladeren = te nat; bruine randen = droge lucht. Veeg de grote bladeren regelmatig schoon.",
    ),
    "Philodendron Brasil": (
        "Helder, indirect licht voor de gele middenstreep.",
        "Laat de bovenste 2-3 cm opdrogen; ongeveer eens per week.",
        "Normale kamerlucht is prima.",
        "Ideaal 18-27°C.",
        "Elke 2-4 weken in voorjaar en zomer met kamerplantenvoeding op halve sterkte.",
        "Om de 1-2 jaar; stekken wortelen makkelijk in water.",
        "Volledig groene bladeren = te weinig licht (knip die ranken terug); gele bladeren = te nat.",
    ),
    "Alocasia Black Velvet": (
        "Helder, indirect licht; directe zon verbrandt het fluweelblad.",
        "Laat de bovenste 2-3 cm opdrogen; houd de grond verder licht vochtig. Kleiner en dus sneller te nat dan andere Alocasia's.",
        "Houdt van 60%+ luchtvochtigheid.",
        "Ideaal 18-27°C; niet onder 16°C.",
        "Eens per maand in voorjaar en zomer met kamerplantenvoeding op halve sterkte.",
        "Om de 2 jaar in zeer luchtige mix met schors en perliet in een kleine pot.",
        "Bladval in de winter kan rust zijn. Gespikkeld blad = spint.",
    ),
    "Alocasia Zebrina": (
        "Helder, indirect licht; een paar uur ochtendzon mag.",
        "Laat de bovenste 3-5 cm opdrogen; gevoelig voor te nat.",
        "Houdt van 60%+ luchtvochtigheid.",
        "Ideaal 18-27°C; niet onder 16°C.",
        "Elke 2-4 weken in voorjaar en zomer met kamerplantenvoeding op halve sterkte.",
        "Om de 1-2 jaar in luchtige aroidenmix; de hoge stelen kunnen steun nodig hebben.",
        "Omvallende stelen = te weinig licht of te nat. Let op spint.",
    ),
    "Anthurium Clarinervium": (
        "Helder, indirect licht; geen directe zon.",
        "Laat de bovenste 2-3 cm opdrogen; houd het substraat licht vochtig.",
        "Houdt van 60%+ luchtvochtigheid.",
        "Ideaal 18-27°C; niet onder 16°C.",
        "Elke 3-4 weken in voorjaar en zomer met kamerplantenvoeding op halve sterkte.",
        "Om de 2 jaar in zeer luchtige mix (schors, perliet, veenmos).",
        "Vervormde nieuwe bladeren = te droge lucht; bruine plekken = te nat.",
    ),
    "Anthurium Crystallinum": (
        "Helder, indirect licht; geen directe zon.",
        "Laat de bovenste 2-3 cm opdrogen; houd het substraat licht vochtig.",
        "Houdt van 70%+ luchtvochtigheid.",
        "Ideaal 18-27°C; niet onder 16°C.",
        "Elke 3-4 weken in voorjaar en zomer met kamerplantenvoeding op halve sterkte.",
        "Om de 2 jaar in zeer luchtige mix.",
        "Nieuwe bladeren die vastplakken in de schede = te droge lucht.",
    ),
    "Calathea White Fusion": (
        "Helder, indirect licht voor de witte marmering; geen directe zon.",
        "Houd de grond licht vochtig met regenwater of gefilterd water.",
        "Houdt van 60-70% luchtvochtigheid.",
        "Ideaal 18-26°C; niet onder 16°C.",
        "Elke 3-4 weken in voorjaar en zomer met kamerplantenvoeding op halve sterkte.",
        "Om de 1-2 jaar in luchtige potgrond.",
        "Bruine witte delen = droge lucht of kraanwater; een van de gevoeligste Calathea's.",
    ),
    "Raindrop Peperomia": (
        "Helder, indirect licht.",
        "Laat de bovenste helft van de grond opdrogen - de dikke bladeren slaan water op.",
        "Normale kamerlucht is prima.",
        "Ideaal 18-25°C.",
        "Eens per maand in voorjaar en zomer met kamerplantenvoeding op halve sterkte.",
        "Om de 2-3 jaar in luchtige grond.",
        "Zachte stengels = te nat; gerimpelde bladeren = te droog.",
    ),
    "Cupid Peperomia": (
        "Helder, indirect licht voor de bonte tekening.",
        "Laat de bovenste 2-3 cm opdrogen.",
        "Normale tot hogere luchtvochtigheid.",
        "Ideaal 18-25°C.",
        "Eens per maand in voorjaar en zomer met kamerplantenvoeding op halve sterkte.",
        "Om de 2 jaar; ideaal in een hangpot. Stekken wortelen makkelijk.",
        "Groen wordend blad = te weinig licht; zachte stengels = te nat.",
    ),
    "Red Log Peperomia": (
        "Helder, indirect licht; een beetje zon kleurt de stelen roder.",
        "Laat de grond grotendeels opdrogen - vetplantachtig.",
        "Normale kamerlucht is prima.",
        "Ideaal 18-25°C.",
        "Eens per maand in voorjaar en zomer met verdunde voeding.",
        "Om de 2-3 jaar in luchtige grond met perliet.",
        "Zachte, zwarte stengels = te nat.",
    ),
    "Trailing Jade": (
        "Helder, indirect licht of zachte ochtendzon.",
        "Laat de grond grotendeels opdrogen; ongeveer eens per 1-2 weken.",
        "Normale kamerlucht is prima.",
        "Ideaal 18-25°C.",
        "Eens per maand in voorjaar en zomer met verdunde voeding.",
        "Om de 2 jaar in luchtige grond met perliet; mooi als hangplant.",
        "Zachte, glazige blaadjes = te nat; kale ranken = te weinig licht.",
    ),
    "Zebra Plant": (
        "Helder, indirect licht; geen directe zon.",
        "Houd de grond licht vochtig met kalkarm water; nooit laten uitdrogen, want dan vallen de bladeren.",
        "Houdt van 60%+ luchtvochtigheid.",
        "Ideaal 18-26°C; niet onder 15°C.",
        "Elke 2 weken in voorjaar en zomer met bloeivoeding op halve sterkte.",
        "Na de bloei terugsnoeien tot een paar bladparen en verpotten.",
        "Bladval = te droog of te koud; bruine randen = droge lucht.",
    ),
    "Polka Dot Plant": (
        "Helder, indirect licht voor de mooiste stippen.",
        "Houd de grond licht vochtig.",
        "Houdt van 50%+ luchtvochtigheid.",
        "Ideaal 18-25°C.",
        "Eens per maand met kamerplantenvoeding op halve sterkte.",
        "Top regelmatig om een compacte plant te houden; knip bloemaren weg.",
        "Lange, kale stengels = niet getopt of te weinig licht.",
    ),
    "Purple Heart": (
        "Veel licht met wat directe zon voor de diepe paarse kleur.",
        "Laat de bovenste 2-3 cm opdrogen.",
        "Normale kamerlucht is prima.",
        "Ideaal 15-25°C.",
        "Eens per maand in voorjaar en zomer met kamerplantenvoeding op halve sterkte.",
        "Knip regelmatig terug; stekken wortelen makkelijk. Het sap kan de huid irriteren.",
        "Groen wordend blad = te weinig licht; kale ranken = oude plant (vernieuwen via stek).",
    ),
    "Red Aglaonema": (
        "Helder, indirect licht voor de roze-rode kleur; geen directe zon.",
        "Laat de bovenste 2-3 cm opdrogen.",
        "Houdt van 50%+ luchtvochtigheid.",
        "Ideaal 18-27°C; niet onder 16°C.",
        "Elke 4-6 weken in voorjaar en zomer met kamerplantenvoeding op halve sterkte.",
        "Om de 2-3 jaar in luchtige potgrond.",
        "Verbleekte kleur = te weinig licht; bruine randen = droge lucht of kou.",
    ),
    "Lemon Lime Dracaena": (
        "Helder, indirect licht voor de geel-groene strepen.",
        "Laat de bovenste 3-5 cm opdrogen; gebruik bij voorkeur regenwater.",
        "Normale tot hogere luchtvochtigheid.",
        "Ideaal 18-26°C.",
        "Eens per maand in voorjaar en zomer met kamerplantenvoeding.",
        "Om de 2-3 jaar in potgrond met perliet.",
        "Bruine bladpunten = fluoride/kalk of droge lucht.",
    ),
    "Asparagus Fern": (
        "Helder, indirect licht; wat ochtendzon mag.",
        "Houd de grond licht vochtig; de knolwortels slaan wat water op.",
        "Houdt van hogere luchtvochtigheid.",
        "Ideaal 15-24°C.",
        "Elke 2-4 weken in voorjaar en zomer met kamerplantenvoeding op halve sterkte.",
        "Om de 1-2 jaar; de dikke wortels duwen de plant snel uit de pot.",
        "Gele, afvallende naaldjes = te droog of te weinig licht.",
    ),
    "Rabbit's Foot Fern": (
        "Helder, indirect licht.",
        "Laat de bovenste 2 cm opdrogen; geef water op de grond, niet op de harige wortelstokken.",
        "Houdt van 50%+ luchtvochtigheid.",
        "Ideaal 16-24°C.",
        "Eens per maand in voorjaar en zomer met verdunde voeding.",
        "Verpot zelden in een ondiepe pot; begraaf de wortelstokken ('pootjes') niet.",
        "Bruine blaadjes = droge lucht; rottende pootjes = te nat.",
    ),
    "Purple Shamrock": (
        "Helder licht met wat ochtendzon.",
        "Laat de bovenste 2-3 cm opdrogen. Gaat de plant in rust (bladeren sterven af), stop dan een paar weken met water geven.",
        "Normale kamerlucht is prima.",
        "Ideaal 15-24°C.",
        "Elke 2-4 weken in groei met kamerplantenvoeding op halve sterkte.",
        "Verpot de knolletjes na een rustperiode.",
        "Afstervende bladeren = rustperiode, geen ziekte; na een paar weken loopt hij weer uit.",
    ),
    "Lucky Bamboo": (
        "Helder, indirect licht; directe zon verbrandt de bladeren.",
        "Op water: houd de wortels onder water en ververs het elke 1-2 weken (bij voorkeur gefilterd water). In grond: licht vochtig houden.",
        "Normale kamerlucht is prima.",
        "Ideaal 18-26°C.",
        "Eens per 2 maanden een druppel zeer verdunde voeding.",
        "Verplaats naar een grotere vaas of pot als de wortels te vol worden.",
        "Gele stengels = rot (verwijder ze); gele bladeren = te veel zon of chloor in het water.",
    ),
    "Amaryllis": (
        "Helder licht met wat zon tijdens groei en bloei.",
        "Geef na het oppotten spaarzaam water tot er groei is, daarna licht vochtig houden. Na de zomer (augustus-september) stoppen met water geven voor de rustperiode.",
        "Normale kamerlucht.",
        "Ideaal 18-24°C tijdens de groei; rust koel (10-15°C) en droog.",
        "Na de bloei elke 2 weken voeden tot de zomer, om de bol op te laden.",
        "Plant de bol met de bovenste helft boven de grond, in een pot die net iets groter is.",
        "Geen bloei = geen rustperiode of te weinig gevoed na de vorige bloei.",
    ),
    "Clivia": (
        "Helder, indirect licht; geen directe zon.",
        "Laat de bovenste helft van de grond opdrogen. In de winterrust (oktober-januari) bijna droog houden.",
        "Normale kamerlucht is prima.",
        "Ideaal 16-24°C; een koele winterrust (10-12°C) is nodig voor de bloei.",
        "Elke 2-4 weken van voorjaar tot eind zomer met kamerplantenvoeding.",
        "Bloeit het best krap in de pot; verpot alleen als de pot bijna barst.",
        "Bloemen die tussen de bladeren blijven steken = geen koele rust gehad.",
    ),
    "Rain Lily": (
        "Veel licht met directe zon.",
        "Houd de grond licht vochtig in de groei; na een droge periode zorgt een flinke gietbeurt vaak voor bloei.",
        "Normale kamerlucht.",
        "Ideaal 16-26°C.",
        "Elke 2-4 weken in de groei met bloeivoeding op halve sterkte.",
        "Bloeit graag krap; verpot zelden.",
        "Geen bloei = te weinig licht of geen droge periode.",
    ),
    "Jasmine": (
        "Veel licht met wat directe zon.",
        "Houd de grond licht vochtig tijdens groei en bloei.",
        "Houdt van hogere luchtvochtigheid.",
        "Koele nachten (10-15°C) in de winter zijn nodig voor de bloei.",
        "Elke 2 weken in voorjaar en zomer met bloeivoeding.",
        "Na de bloei terugsnoeien en verpotten; geef een klimrek.",
        "Geen bloei = te warme winter; bladval = te droog.",
    ),
    "Gardenia": (
        "Veel helder licht zonder felle middagzon.",
        "Houd de grond licht vochtig met kalkarm water op kamertemperatuur.",
        "Houdt van 60%+ luchtvochtigheid.",
        "Ideaal 18-22°C overdag, 15-18°C 's nachts.",
        "Elke 2 weken in voorjaar en zomer met voeding voor zuurminnende planten.",
        "Om de 2 jaar in zure grond (rododendrongrond).",
        "Knopval = verplaatsen, tocht of droge lucht; gele bladeren = kalk in het water.",
    ),
    "Chinese Hibiscus": (
        "Veel licht met directe zon voor een rijke bloei.",
        "Houd de grond licht vochtig; in de bloeitijd een echte waterdrinker.",
        "Normale tot hogere luchtvochtigheid.",
        "Ideaal 18-26°C; in de winter koeler (15°C) mag.",
        "Elke 2 weken in voorjaar en zomer met bloeivoeding.",
        "Snoei in het voorjaar terug en verpot om de 2 jaar.",
        "Knopval = te droog, verplaatsen of te weinig licht; let op bladluis en spint.",
    ),
    "Passion Flower": (
        "Veel licht met directe zon.",
        "Houd de grond licht vochtig in groei en bloei; in de winter minder.",
        "Normale kamerlucht.",
        "Ideaal 18-26°C; winterrust koeler (10-15°C).",
        "Elke 2 weken in voorjaar en zomer met bloeivoeding.",
        "Snoei in het voorjaar terug en geef een klimrek.",
        "Geen bloei = te weinig licht of te veel stikstof.",
    ),
    "Boat Lily": (
        "Helder licht met wat ochtendzon voor de paarse onderkant.",
        "Laat de bovenste 2-3 cm opdrogen.",
        "Normale kamerlucht is prima.",
        "Ideaal 16-26°C.",
        "Eens per maand in voorjaar en zomer met kamerplantenvoeding op halve sterkte.",
        "Om de 1-2 jaar; uitlopers kun je apart zetten.",
        "Verbleekte kleur = te weinig licht; zachte voet = te nat.",
    ),
    "Peperomia Hope": (
        "Helder, indirect licht.",
        "Laat de grond grotendeels opdrogen; de ronde blaadjes slaan water op.",
        "Normale kamerlucht is prima.",
        "Ideaal 18-25°C.",
        "Eens per maand in voorjaar en zomer met verdunde voeding.",
        "Om de 2 jaar in luchtige grond; mooi als hangplant.",
        "Zachte stengels = te nat; kale ranken = te weinig licht.",
    ),
    "Silver Pothos": (
        "Helder tot matig indirect licht; meer licht geeft meer zilver.",
        "Laat de bovenste 3-5 cm opdrogen; de bladeren krullen iets bij dorst.",
        "Normale tot hogere luchtvochtigheid.",
        "Ideaal 18-27°C.",
        "Elke 3-4 weken in voorjaar en zomer met kamerplantenvoeding op halve sterkte.",
        "Om de 2 jaar in luchtige potgrond; hangend of klimmend.",
        "Gele bladeren = te nat; krullende bladeren = dorst.",
    ),
    "Philodendron Micans": (
        "Helder, indirect licht voor de fluweelglans; geen directe zon.",
        "Laat de bovenste 2-3 cm opdrogen.",
        "Houdt van 50%+ luchtvochtigheid.",
        "Ideaal 18-27°C.",
        "Elke 2-4 weken in voorjaar en zomer met kamerplantenvoeding op halve sterkte.",
        "Om de 1-2 jaar; stekken wortelen makkelijk.",
        "Kleine bladeren en lange stelen = te weinig licht.",
    ),
    "Peace Lily 'Domino'": (
        "Helder, indirect licht voor de witte vlekken; geen directe zon.",
        "Houd de grond licht vochtig; laat de bovenste 2 cm opdrogen.",
        "Houdt van 50%+ luchtvochtigheid.",
        "Ideaal 18-26°C.",
        "Elke 2-4 weken in voorjaar en zomer met kamerplantenvoeding op halve sterkte.",
        "Om de 1-2 jaar in humusrijke potgrond.",
        "Groen wordend blad = te weinig licht; bruine punten = kalk of droge lucht.",
    ),
    "Dwarf Umbrella Tree": (
        "Helder, indirect licht.",
        "Laat de bovenste 2-3 cm opdrogen.",
        "Normale kamerlucht; droge lucht geeft spint.",
        "Ideaal 16-24°C.",
        "Elke 2-4 weken in voorjaar en zomer met kamerplantenvoeding.",
        "Om de 2 jaar; snoei om hem compact te houden.",
        "Bladval = te nat of te donker.",
    ),
    "Ponytail Palm (dwarf)": (
        "Veel licht met directe zon.",
        "Laat de grond helemaal opdrogen; de stamvoet slaat water op.",
        "Droge lucht is prima.",
        "Ideaal 18-27°C; in de winter koeler en droger.",
        "Eens per maand in voorjaar en zomer met verdunde voeding.",
        "Verpot zelden, in een ondiepe pot met cactusgrond.",
        "Zachte stamvoet = te nat.",
    ),
    "Bunny Ear Cactus": (
        "Volle zon.",
        "In de zomer water als de grond helemaal droog is; in de winter droog houden.",
        "Droge lucht is prima.",
        "Groeiseizoen 20-30°C; winterrust koel (5-12°C).",
        "Eens per maand in voorjaar en zomer met cactusvoeding.",
        "Om de 2-3 jaar; pas op voor de fijne glochiden (tang en krant gebruiken).",
        "Zachte, bruine schijven = te nat of te koud.",
    ),
    "Christmas Kalanchoe": (
        "Helder licht met wat zon.",
        "Laat de bovenste 2-3 cm opdrogen; nooit water in de schotel.",
        "Normale kamerlucht; niet besproeien.",
        "Ideaal 15-22°C; koel staan verlengt de bloei.",
        "Na de bloei elke 2-4 weken met kamerplantenvoeding op halve sterkte.",
        "Voor een nieuwe bloei: vanaf september 6 weken lang elke dag 14 uur volledig donker (kortedagplant).",
        "Meeldauw bij te vochtige lucht; rot bij te veel water.",
    ),
    "Bunny Succulent": (
        "Veel licht met zon.",
        "Groeit in de koele maanden: in herfst en winter water als de grond droog is. In de zomer vrijwel droog houden (rust).",
        "Droge lucht is prima.",
        "Houdt van koel: 10-20°C.",
        "Nauwelijks nodig.",
        "Verpot tijdens de rust in cactusgrond.",
        "Afsterven in de zomer = normale rust.",
    ),
    "Banana Plant": (
        "Zoveel mogelijk licht met directe zon.",
        "Een echte waterdrinker: houd de grond constant vochtig in de zomer.",
        "Houdt van hogere luchtvochtigheid.",
        "Ideaal 20-30°C; niet onder 12°C.",
        "Elke week in de zomer met kamerplantenvoeding.",
        "Elk voorjaar een grotere pot; groeit zeer snel.",
        "Gescheurde bladeren zijn natuurlijk; bruine randen = droge lucht.",
    ),
    "Canary Island Date Palm": (
        "Zoveel mogelijk licht met directe zon; 's zomers graag buiten.",
        "Laat de bovenste 3-5 cm opdrogen.",
        "Normale kamerlucht.",
        "Ideaal 15-25°C; winter koel (5-10°C).",
        "Eens per maand in voorjaar en zomer met palmvoeding.",
        "Om de 2-3 jaar in een zware pot. Pas op voor de scherpe stekels aan de bladvoet.",
        "Bruine punten = droge lucht; gele bladeren = te nat.",
    ),
    "Pygmy Date Palm": (
        "Veel helder licht met wat zon.",
        "Houd de grond licht vochtig.",
        "Houdt van hogere luchtvochtigheid.",
        "Ideaal 18-26°C.",
        "Eens per maand in voorjaar en zomer met palmvoeding.",
        "Om de 2-3 jaar.",
        "Bruine bladpunten = droge lucht; gele bladeren = magnesiumgebrek.",
    ),
    "European Fan Palm": (
        "Volle zon; 's zomers graag buiten.",
        "Laat de bovenste helft van de grond opdrogen.",
        "Droge lucht is prima.",
        "Verdraagt kou tot ongeveer -5°C; binnen liefst een koele winter.",
        "Eens per maand in voorjaar en zomer met palmvoeding.",
        "Om de 2-3 jaar in een zware pot.",
        "Bruine punten = te droge lucht binnen; let op spint.",
    ),
    "Room Lime": (
        "Veel helder licht zonder felle middagzon.",
        "Houd de grond constant vochtig; een echte waterdrinker in de zomer.",
        "Normale tot hogere luchtvochtigheid.",
        "Houdt van koel: 10-20°C.",
        "Elke week in voorjaar en zomer met kamerplantenvoeding.",
        "Elk voorjaar verpotten en terugsnoeien.",
        "Gele bladeren = te warm of te droog; let op witte vlieg.",
    ),
    "Rose Grape": (
        "Veel helder licht zonder directe zon.",
        "Houd de grond licht vochtig met regenwater; in de winter iets droger.",
        "Houdt van 70%+ luchtvochtigheid.",
        "Ideaal 20-25°C; winterrust bij 16-18°C voor bloei.",
        "Elke 2 weken in voorjaar en zomer met bloeivoeding.",
        "Na de bloei verpotten in luchtige, humusrijke grond.",
        "Knopval = te droge lucht of verplaatsen.",
    ),
    "Fishtail Palm": (
        "Helder, indirect licht.",
        "Houd de grond licht vochtig.",
        "Houdt van 60%+ luchtvochtigheid.",
        "Ideaal 18-27°C; niet onder 15°C.",
        "Eens per maand in voorjaar en zomer met palmvoeding.",
        "Om de 2-3 jaar.",
        "Bruine bladpunten = droge lucht.",
    ),
    "Lemon Tree (potted)": (
        "Zoveel mogelijk direct licht; van mei tot oktober graag buiten in de zon.",
        "Geef grondig water zodra de bovenste 2-3 cm droog is; laat nooit water in de schotel staan.",
        "Houdt van gemiddelde luchtvochtigheid.",
        "Zomer 18-30°C; winter koel (5-12°C) en licht.",
        "Elke 2 weken in voorjaar en zomer met citrusvoeding.",
        "Om de 2-3 jaar in citrusgrond.",
        "Gele bladeren met groene nerven = ijzer- of magnesiumgebrek; bladval in de winter = te warm en te donker.",
    ),
    "Orchid Cactus": (
        "Helder, indirect licht met ochtendzon.",
        "Houd de grond licht vochtig in de groei; na de bloei een drogere rust.",
        "Houdt van gemiddelde tot hogere luchtvochtigheid.",
        "Ideaal 18-26°C; winterrust bij 10-15°C voor bloei.",
        "Elke 2 weken in voorjaar en zomer met bloeivoeding.",
        "Bloeit het best krap; verpot zelden in luchtige mix met schors.",
        "Geen bloei = geen koele rust; rode leden = te veel zon.",
    ),
    "Kris Plant": (
        "Helder, indirect licht; geen directe zon.",
        "Laat de bovenste 2-3 cm opdrogen; houd verder licht vochtig.",
        "Houdt van 60%+ luchtvochtigheid.",
        "Ideaal 18-27°C; niet onder 16°C.",
        "Elke 2-4 weken in voorjaar en zomer met kamerplantenvoeding op halve sterkte.",
        "Om de 1-2 jaar in luchtige aroidenmix.",
        "Bladval in de winter = rust; gespikkeld blad = spint.",
    ),
}
