"""Soortspecifieke Nederlandse verzorgingsgidsen - deel 1: vetplanten,
woestijncactussen en droogtetolerante planten.

Elke waarde is een tuple met 7 teksten, in deze volgorde:
(licht, water geven, luchtvochtigheid, temperatuur, bemesten, verpotten,
veelvoorkomende problemen). Giftigheid komt apart uit TOXICITY in
generate_species_data.py.
"""

GUIDES = {
    "Jade Plant": (
        "Zet het geldboompje op de lichtste plek die je hebt, het liefst een zuid- of westraam met een paar uur directe zon. Met genoeg zon krijgen de bladranden vaak een mooi rood randje; bij te weinig licht wordt de plant slap en scheef.",
        "Geef pas water als de grond helemaal droog is - in de zomer ongeveer elke 2-3 weken, in de winter hooguit eens per maand. Geef dan grondig water en giet wat in de schotel blijft staan na 15 minuten weg. Gerimpelde bladeren betekenen dorst; zachte, gele bladeren te veel water.",
        "Droge kamerlucht is geen probleem; besproeien is niet nodig en werkt schimmel eerder in de hand.",
        "Groeit het best bij 18-24°C. Een koele, droge winterrust (10-15°C) bevordert de kans op de kleine witte stervormige bloempjes. Niet onder 5°C.",
        "Van april tot september eens per maand cactus-/vetplantenvoeding op halve sterkte; in de winter niet bemesten.",
        "Om de 2-3 jaar in het voorjaar in cactusgrond met extra grit of perliet. Kies een zware, stenen of terracotta pot: de plant wordt kopzwaar. Stekken (blad of tak) laten na een paar dagen drogen makkelijk wortelen.",
        "Afvallende bladeren en een zachte stam wijzen op te veel water of kou; witte wollige plukjes in de bladoksels zijn wolluis - dep die met een wattenstaafje met spiritus.",
    ),
    "String of Pearls": (
        "Helder licht met een paar uur zachte ochtend- of avondzon. Felle middagzon achter glas kan de parels verbranden, maar in een donkere hoek groeit de plant kaal en ijl.",
        "Laat de grond bijna helemaal opdrogen; de parels slaan zelf water op. Gemiddeld eens per 10-14 dagen in de zomer en eens per 3-4 weken in de winter. Platte, gerimpelde parels = dorst; doorschijnende, papperige parels = te nat.",
        "Normale tot droge kamerlucht is prima; niet besproeien.",
        "Het prettigst bij 18-24°C, in de winter mag het koeler (12-15°C) - dat stimuleert de geurige witte bloempjes. Niet onder 7°C.",
        "Eens per maand in voorjaar en zomer vetplantenvoeding op halve sterkte; de rest van het jaar niet.",
        "Verpot alleen als het echt nodig is, in een ondiepe, brede terracotta pot met snel drainerende cactusgrond. De ranken zijn breekbaar: verpot voorzichtig. Afgebroken stukjes wortelen makkelijk als je ze op vochtige grond legt.",
        "Een kale, verdroogde bovenkant ontstaat vaak door te weinig licht of doordat de plant daar te nat blijft staan (stengelrot aan de voet). Stek dan gezonde ranken opnieuw.",
    ),
    "String of Bananas": (
        "Helder licht met wat directe ochtendzon; iets toleranter voor licht dan String of Pearls. Te weinig licht geeft lange, kale ranken met ver uit elkaar staande 'bananen'.",
        "Laat de grond tussen de beurten door vrijwel helemaal opdrogen - ongeveer eens per 10-14 dagen in de zomer, eens per 3-4 weken in de winter. Gerimpelde bananen betekenen dorst.",
        "Droge kamerlucht is prima; niet besproeien.",
        "Houdt van 18-26°C; in de winter liever wat koeler (12-15°C) en droger. Niet onder 7°C.",
        "Eens per maand in het groeiseizoen vetplantenvoeding op halve sterkte.",
        "Om de 2 jaar in het voorjaar in een hangpot met cactusgrond en extra perliet. Groeit snel; lange ranken kun je terugknippen en als stek gebruiken.",
        "Zachte, glazige blaadjes en zwarte stengels aan de voet wijzen op rot door te nat staan. Let ook op wolluis tussen de dicht op elkaar staande blaadjes.",
    ),
    "String of Dolphins": (
        "Helder licht met een paar uur zachte zon; de 'dolfijnvinnen' worden het mooist bij veel licht. In te weinig licht verliezen de blaadjes hun typische vorm.",
        "Laat de grond grotendeels opdrogen; in de zomer ongeveer eens per 7-10 dagen, in de winter eens per 3-4 weken. Iets dorstiger dan String of Pearls, maar natte voeten zijn fataal.",
        "Normale kamerlucht volstaat; niet besproeien.",
        "Ideaal 18-24°C, 's winters koeler (10-15°C) mag. Beschermen tegen tocht en vorst.",
        "Eens per maand in voorjaar en zomer verdunde vetplantenvoeding.",
        "Verpot om de 1-2 jaar in het voorjaar in een kleine, goed drainerende pot met cactusgrond. Stekken van 5-10 cm wortelen snel.",
        "Gele, zachte blaadjes = te veel water; lange, dunne stengels met weinig blad = te weinig licht. Kan gevoelig zijn voor bladluis op jonge scheuten.",
    ),
    "String of Hearts": (
        "Helder, indirect licht tot wat directe ochtendzon. Meer licht geeft een diepere paars-zilveren tekening en dichter blad; bij weinig licht worden de ranken lang en kaal.",
        "Laat de grond tussen de beurten helemaal opdrogen - de plant heeft kleine knolletjes waarin ze water opslaat. In de zomer ongeveer eens per 1-2 weken, in de winter eens per 3-4 weken.",
        "Gewone kamerlucht is prima; besproeien is niet nodig.",
        "Het prettigst tussen 18-26°C. In de winter kouder (12-15°C) en droger houden mag, maar niet onder 10°C.",
        "Eens per maand van april tot september met kamerplanten- of vetplantenvoeding op halve sterkte.",
        "Groeit graag wat krap in de pot; verpot om de 2-3 jaar in een ondiepe pot met cactusgrond gemengd met wat gewone potgrond. Knolletjes aan de ranken kun je op grond leggen om nieuwe plantjes te maken.",
        "Gele, slappe blaadjes en zachte ranken wijzen op te veel water. Veel bladval na een verhuizing is meestal tijdelijke stress.",
    ),
    "String of Turtles": (
        "Helder, indirect licht; geen felle directe zon, want de dunne blaadjes verbranden snel. Te donker geeft uitgerekte ranken en een vervagende 'schildpadtekening'.",
        "Anders dan echte vetplanten wil deze Peperomia niet volledig uitdrogen: geef water zodra de bovenste 1-2 cm droog is, ongeveer eens per week in de zomer. Nooit water in de schotel laten staan.",
        "Houdt van iets hogere luchtvochtigheid (50%+); zet de plant bijvoorbeeld in een lichte badkamer of bij andere planten.",
        "Ideaal 18-24°C; niet onder 15°C en weg van koude tocht.",
        "Eens per maand in het groeiseizoen kamerplantenvoeding op kwart- tot halve sterkte - de plant heeft weinig nodig.",
        "Verpot zelden (om de 2-3 jaar) in een ondiepe pot met luchtige potgrond met extra perliet. Stekjes van een paar blaadjes wortelen makkelijk op vochtige grond.",
        "Verschrompelde blaadjes = te droog of te droge lucht; glazige, zwarte stengels = te nat. Groeit van nature langzaam, dat is geen probleem.",
    ),
    "Burro's Tail": (
        "Veel licht met een paar uur directe zon (liefst ochtend- of avondzon). Te weinig licht maakt de 'staarten' dun en de blaadjes bleek en ver uit elkaar.",
        "Laat de grond helemaal opdrogen voor je weer water geeft - in de zomer ongeveer eens per 2 weken, in de winter eens per maand of minder. Gerimpelde blaadjes betekenen dorst.",
        "Droge kamerlucht is ideaal; niet besproeien, want water tussen de blaadjes geeft snel rot.",
        "Houdt van 18-26°C; een koelere winter (10-15°C) is prima. Niet onder 5°C.",
        "Eens per maand van voorjaar tot eind zomer met verdunde cactusvoeding.",
        "Verpot zo min mogelijk: de blaadjes vallen bij de minste aanraking af. Kies meteen een hangpot met cactusgrond en ruime drainage. Afgevallen blaadjes kun je op droge grond leggen - ze vormen vaak zelf wortels.",
        "Veel bladval komt meestal door aanraken of verplaatsen, niet door ziekte. Zachte, doorschijnende blaadjes en een rottende voet wijzen op te veel water.",
    ),
    "Panda Plant": (
        "Veel licht, gerust met een paar uur directe zon. De bruine randjes aan de viltige bladpunten worden dan het mooist; in te weinig licht wordt de plant slap en groen.",
        "Laat de grond volledig opdrogen; geef in de zomer ongeveer eens per 2 weken water en in de winter eens per 3-4 weken. Giet op de grond, niet over de harige bladeren.",
        "Droge kamerlucht is prima; niet besproeien - vocht blijft in de haartjes hangen en kan vlekken of rot geven.",
        "Ideaal 18-26°C; 's winters mag het koeler, maar niet onder 10°C.",
        "Eens per maand in voorjaar en zomer met cactus-/vetplantenvoeding op halve sterkte.",
        "Om de 2-3 jaar in het voorjaar in cactusgrond met extra perliet. Een afgebroken blad of topstek wortelt makkelijk na een paar dagen drogen.",
        "Zachte, zwarte bladvoeten wijzen op rot door te veel water; lange, dunne stelen op te weinig licht. Stof kun je met een zacht kwastje uit het vilt borstelen.",
    ),
    "Flaming Katy": (
        "Helder licht met wat directe zon, bijvoorbeeld een oost- of westraam. Bloeit het langst in helder licht zonder hete middagzon achter glas.",
        "Laat de bovenste 2-3 cm van de grond opdrogen tussen de beurten door - in de bloeitijd ongeveer eens per week, daarna minder. Nooit water in de schotel laten staan.",
        "Gewone kamerlucht is prima; niet besproeien, vooral niet op de bloemen.",
        "Het prettigst bij 15-22°C; koeler staan verlengt de bloei. Niet onder 10°C.",
        "Eens per 2-4 weken na de bloei in voorjaar en zomer met kamerplantenvoeding op halve sterkte; niet tijdens de rustperiode in de herfst.",
        "Knip na de bloei uitgebloeide stelen weg en verpot eventueel in voorjaar in cactusgrond gemengd met potgrond. Voor een nieuwe bloei: vanaf september zo'n 6 weken lang elke dag 14 uur volledig donker zetten (kortedagplant).",
        "Meeldauw (wit poeder op de bladeren) komt door te vochtige, stilstaande lucht; rottende stelen door te veel water. Veel bladeren maar geen bloemen betekent dat de donkere periode ontbrak.",
    ),
    "Elephant Bush": (
        "Veel licht met directe zon; een zuidraam of 's zomers buiten op een beschutte plek is ideaal. Bij te weinig licht wordt de groei lang en slap en vallen blaadjes af.",
        "Laat de grond tussen de beurten door opdrogen; in de zomer ongeveer eens per 1-2 weken, in de winter eens per 3-4 weken. Iets minder kieskeurig dan veel andere vetplanten.",
        "Droge kamerlucht is geen probleem.",
        "Houdt van warmte (18-28°C); in de winter koeler mag, maar niet onder 7°C.",
        "Eens per maand in het groeiseizoen met verdunde vetplantenvoeding.",
        "Om de 2-3 jaar in het voorjaar in cactusgrond; een ondiepe pot past bij bonsai-vormgeving. Snoei gerust om de plant compact te houden - takjes wortelen makkelijk als stek.",
        "Massale bladval na een koude of donkere periode is een stressreactie; zet de plant lichter en warmer. Zachte stam = te nat.",
    ),
    "Pencil Cactus": (
        "Zoveel mogelijk licht met directe zon; een zuidraam is ideaal. Bij weinig licht worden de takjes dun en slap.",
        "Laat de grond volledig uitdrogen; in de zomer ongeveer eens per 2-3 weken, in de winter vrijwel niet (eens per 4-6 weken).",
        "Droge lucht is prima.",
        "Warm (18-28°C); in de winter niet onder 10°C.",
        "Eens per maand in voorjaar en zomer met cactusvoeding op halve sterkte.",
        "Verpot om de 2-3 jaar in cactusgrond in een zware pot. Draag handschoenen en een bril: het witte melksap is sterk irriterend voor huid en ogen. Spoel gereedschap na afloop af.",
        "Zachte, bruine takken aan de voet wijzen op rot door te veel water; takken die afbreken of uitdrogen op te weinig licht of kou.",
    ),
    "African Milk Tree": (
        "Veel licht met een paar uur directe zon. De roodbladige vorm ('Rubra') kleurt alleen mooi bij veel licht. Draai de pot af en toe zodat hij recht groeit.",
        "Laat de grond volledig opdrogen tussen de beurten - in de zomer ongeveer eens per 2 weken, in de winter eens per maand of minder.",
        "Droge kamerlucht is prima.",
        "Ideaal 18-27°C; niet onder 10°C. Koude, natte grond is de grootste bedreiging.",
        "Eens per maand in het groeiseizoen met verdunde cactusvoeding.",
        "Verpot om de 2-3 jaar in een zware, stabiele pot met cactusgrond; de plant wordt snel kopzwaar. Gebruik handschoenen: het melksap irriteert huid en ogen.",
        "Afvallende blaadjes in de winter zijn normaal. Bruine, verkurkte plekken onderaan de stam zijn meestal natuurlijke veroudering; zachte, donkere plekken wijzen op rot.",
    ),
    "String of Buttons": (
        "Helder licht met een paar uur zon; de bladranden kleuren dan roze-rood. Bij te weinig licht strekken de 'knoopjes' zich uit.",
        "Laat de grond volledig opdrogen; ongeveer eens per 2 weken in de zomer, eens per 3-4 weken in de winter. Giet op de grond, niet tussen de gestapelde blaadjes.",
        "Droge lucht is prima; niet besproeien.",
        "Ideaal 18-25°C, in de winter koeler (10-15°C).",
        "Eens per maand in voorjaar en zomer met vetplantenvoeding op halve sterkte.",
        "Om de 2 jaar in het voorjaar in een ondiepe pot met cactusgrond. Omgevallen stengels kun je als stek opnieuw planten.",
        "Rot tussen de dicht op elkaar staande blaadjes komt door water dat blijft staan; wolluis verstopt zich graag in de bladoksels.",
    ),
    "Ghost Plant": (
        "Veel licht met directe zon; dan kleuren de rozetten roze-lila. In te weinig licht worden ze grijsgroen en rekken ze uit.",
        "Laat de grond volledig opdrogen; ongeveer eens per 2 weken in de zomer, eens per maand in de winter.",
        "Droge lucht is prima.",
        "Ideaal 15-26°C; verdraagt koelere winters tot ongeveer 5°C mits droog.",
        "Eens per maand in voorjaar en zomer met verdunde vetplantenvoeding - niet te veel, dan verliest hij zijn kleur.",
        "Om de 2 jaar in het voorjaar in cactusgrond. De bladeren vallen makkelijk af; elk afgevallen blad kan een nieuw plantje vormen.",
        "Lange, hangende stelen met rozetten aan het eind zijn normaal bij oudere planten - knip de rozet af en stek hem opnieuw. Zachte bladeren = te nat.",
    ),
    "Moonstones": (
        "Veel licht met directe zon; de dikke, bepoederde blaadjes kleuren dan zacht roze-blauw.",
        "Laat de grond helemaal opdrogen en geef dan pas water; zo'n eens per 2-3 weken in de zomer, eens per maand of minder in de winter. Giet niet over de bladeren.",
        "Droge lucht is prima; nooit besproeien - dat beschadigt de beschermende waslaag.",
        "Ideaal 15-26°C; niet onder 5°C.",
        "Eens per maand in het groeiseizoen met verdunde cactusvoeding, of helemaal niet in voedzame grond.",
        "Om de 2-3 jaar in het voorjaar in zeer goed drainerende cactusgrond. Raak de bladeren zo min mogelijk aan: vingerafdrukken blijven zichtbaar in de waslaag.",
        "Rimpelige bladeren = dorst; doorschijnende, zachte bladeren = te veel water. Uitgerekte groei = te weinig licht.",
    ),
    "Hens and Chicks": (
        "Zoveel mogelijk directe zon. Binnen blijft deze winterharde plant het mooist op een zuidraam; hij doet het eigenlijk het best buiten.",
        "Laat de grond volledig opdrogen; ongeveer eens per 2-3 weken in de zomer, in de winter nauwelijks.",
        "Droge lucht is ideaal.",
        "Verdraagt veel: van vorst tot hitte. Binnen is een koele winterrust (5-10°C) gezonder dan een warme kamer.",
        "Bemesten is nauwelijks nodig; hooguit één keer in het voorjaar een lichte gift cactusvoeding.",
        "Verpot in het voorjaar in een brede, ondiepe schaal met grove, zanderige grond. Haal de 'kuikentjes' (uitlopers) los en plant ze apart.",
        "Een rozet die na de bloei afsterft is normaal - dat is de moederplant; de kuikentjes nemen het over. Lange, open rozetten = te weinig licht.",
    ),
    "Zebra Haworthia": (
        "Helder licht met hooguit wat ochtendzon; verdraagt ook een lichte plek zonder directe zon. Felle middagzon kleurt de bladeren rood-bruin.",
        "Laat de grond helemaal opdrogen; ongeveer eens per 2-3 weken in de zomer, eens per maand in de winter. Geef geen water in het hart van de rozet.",
        "Droge kamerlucht is prima.",
        "Ideaal 18-25°C; in de winter mag het koeler, niet onder 10°C.",
        "Eens per maand in voorjaar en zomer met verdunde cactusvoeding.",
        "Om de 2-3 jaar in een kleine, ondiepe pot met cactusgrond. Uitlopers aan de voet kun je bij het verpotten losmaken en apart zetten.",
        "Doorschijnende, zachte bladeren = te veel water; bruine, droge bladpunten zijn meestal onschuldig of wijzen op te felle zon.",
    ),
    "Haworthia (Pearl Plant)": (
        "Helder, indirect licht of zachte ochtendzon; een van de weinige vetplanten die het ook goed doet zonder volle zon.",
        "Laat de grond volledig opdrogen tussen de beurten; eens per 2-3 weken in de zomer, eens per maand in de winter.",
        "Normale kamerlucht is prima.",
        "Ideaal 18-25°C; niet onder 10°C.",
        "Eens per maand in het groeiseizoen met verdunde cactusvoeding.",
        "Groeit langzaam; verpot om de 2-3 jaar in een ondiepe pot met cactusgrond. Deel de uitlopers bij het verpotten.",
        "Zachte, gele bladeren onderaan = te nat; rode of bruine verkleuring = te veel zon (verplaats iets verder van het raam).",
    ),
    "Ox Tongue Plant": (
        "Helder, indirect licht; verdraagt minder licht dan de meeste vetplanten. Te veel directe zon geeft rode, gevlekte bladeren.",
        "Laat de grond grotendeels opdrogen; ongeveer eens per 2 weken in de zomer, eens per 3-4 weken in de winter.",
        "Droge kamerlucht is prima.",
        "Ideaal 16-25°C; een koelere winter (10-15°C) is goed.",
        "Eens per maand in voorjaar en zomer met verdunde cactusvoeding.",
        "Groeit langzaam; om de 2-3 jaar verpotten in cactusgrond. Uitlopers en bladstekken slaan makkelijk aan.",
        "Zwarte, zachte plekken wijzen op te veel water; kurkachtige bruine vlekjes zijn vaak onschuldige littekens.",
    ),
    "Desert Rose": (
        "Zoveel mogelijk directe zon - minimaal 6 uur per dag voor bloei. Een zuidraam of 's zomers buiten in de zon is ideaal.",
        "Geef in de zomer grondig water zodra de grond droog is (ongeveer eens per week bij warm weer). In de winterrust nauwelijks water: eens per 3-4 weken of minder.",
        "Droge lucht is prima.",
        "Houdt van warmte: 20-30°C. In de winter niet onder 12°C; kou plus natte grond is fataal.",
        "Van voorjaar tot eind zomer elke 2-3 weken met een fosforrijke (bloei)voeding op halve sterkte.",
        "Om de 2-3 jaar in het voorjaar in grove cactusgrond. Bij het verpotten kun je de verdikte stamvoet (caudex) iets hoger zetten voor een mooie vorm. Draag handschoenen: het sap is giftig.",
        "Bladval in de herfst is een normale rustreactie. Een zachte caudex wijst op rot door te veel water in de koude periode; let ook op spint en wolluis.",
    ),
    "Golden Barrel Cactus": (
        "Volle zon, zoveel mogelijk; een zuidraam of 's zomers buiten. Wen de plant geleidelijk aan buitenzon om verbranding te voorkomen.",
        "Van april tot september grondig water geven zodra de grond helemaal droog is (ongeveer eens per 2-3 weken). Van oktober tot maart vrijwel droog houden.",
        "Droge lucht is ideaal.",
        "Groeiseizoen 20-30°C; winterrust koel en droog bij 8-12°C.",
        "Eens per maand in voorjaar en zomer met cactusvoeding.",
        "Om de 3-4 jaar in een iets grotere pot met minerale cactusgrond. Pak de plant vast met een opgevouwen krant of dikke handschoenen.",
        "Een zachte, verkleurde voet = rot door te veel water; een langer wordende, smallere top = te weinig licht. Geelbruine vlekken aan de zonkant zijn zonnebrand.",
    ),
    "Prickly Pear Cactus": (
        "Volle zon; hoe meer licht, hoe compacter de schijven. Bij te weinig licht worden de nieuwe schijven dun en slap.",
        "In de zomer grondig water geven als de grond helemaal droog is (ongeveer eens per 2 weken). In de winter droog houden.",
        "Droge lucht is prima.",
        "Groeiseizoen 20-30°C; winterrust koel (5-12°C) en droog.",
        "Eens per maand in voorjaar en zomer met cactusvoeding.",
        "Om de 2-3 jaar in cactusgrond. Pas op: de fijne stekeltjes (glochiden) laten bij de minste aanraking los en zijn lastig uit de huid te halen - gebruik een tang en plakband.",
        "Zachte, bruine schijven = te nat of te koud; witte donzige plekjes = wolluis of schildluis.",
    ),
    "Pincushion Cactus": (
        "Zoveel mogelijk licht met directe zon; een zuidraam is ideaal voor de bloei.",
        "In voorjaar en zomer water geven als de grond droog is (ongeveer eens per 2 weken). Van oktober tot maart vrijwel droog houden.",
        "Droge lucht is prima.",
        "Groeiseizoen 20-28°C; een koele, droge winterrust bij 5-12°C is nodig voor de bloemkransjes in het voorjaar.",
        "Eens per maand in het groeiseizoen met cactusvoeding.",
        "Om de 2-3 jaar in een ondiepe pot met minerale cactusgrond. Pollen met uitlopers kun je bij het verpotten delen.",
        "Geen bloei betekent meestal een te warme winter. Rot aan de voet komt door te veel water; wolluis nestelt zich graag tussen de tepels.",
    ),
    "Old Lady Cactus": (
        "Volle zon; de witte haren beschermen de plant tegen fel licht.",
        "In de zomer eens per 2-3 weken grondig water geven als de grond helemaal droog is; giet op de grond, niet over de haren. In de winter droog houden.",
        "Droge lucht is prima.",
        "Groeiseizoen 20-28°C; winterrust koel (5-12°C) en droog - dat geeft in het voorjaar een krans roze bloempjes.",
        "Eens per maand in het groeiseizoen met cactusvoeding.",
        "Om de 2-3 jaar in cactusgrond met extra grit.",
        "Grijze, samengeklonterde haren komen door water gieten over de plant. Rot aan de voet = te nat.",
    ),
    "Star Cactus": (
        "Veel licht; wen geleidelijk aan directe zon. Een zuidraam is ideaal.",
        "In de zomer grondig water geven zodra de grond droog is (eens per 2-3 weken). Van oktober tot maart helemaal droog houden - deze cactus is extra gevoelig voor rot.",
        "Droge lucht is prima.",
        "Groeiseizoen 20-30°C; winterrust droog bij 8-12°C.",
        "Eens per maand in voorjaar en zomer met cactusvoeding op halve sterkte.",
        "Verpot zelden, in minerale cactusgrond (veel puimsteen of lavagrit) en zet de voet niet te diep.",
        "Zachte, bruine voet = rot door te veel water. De witte stippen op de huid zijn normaal - niet wegpoetsen.",
    ),
    "Goat's Horn Cactus": (
        "Veel licht met directe zon; zonder genoeg licht blijven de gekromde stekels klein.",
        "In de zomer eens per 2-3 weken water geven als de grond droog is; in de winter helemaal droog.",
        "Droge lucht is prima.",
        "Groeiseizoen 20-30°C; winterrust bij 8-12°C.",
        "Eens per maand in voorjaar en zomer met verdunde cactusvoeding.",
        "Verpot zelden in minerale cactusgrond; wees voorzichtig met de breekbare, gekromde stekels.",
        "Rot aan de voet door te veel water is het grootste risico. Bloeit met grote gele bloemen na een koele, droge winter.",
    ),
    "Peanut Cactus": (
        "Veel licht met directe zon; bij te weinig licht worden de 'pinda's' lang en slap.",
        "In de zomer water geven als de grond droog is (ongeveer eens per 1-2 weken); in de winter droog houden.",
        "Droge lucht is prima.",
        "Groeiseizoen 20-28°C; een koude winterrust (4-10°C) is nodig voor de knaloranje bloei in het voorjaar.",
        "Eens per maand in voorjaar en zomer met cactusvoeding.",
        "Om de 2 jaar in een brede, ondiepe pot; losse leden wortelen makkelijk als stek.",
        "Spint (fijne webjes, grijze verkleuring) is een bekend probleem bij warme, droge lucht; geen bloei = te warme winter.",
    ),
    "Torch Cactus": (
        "Volle zon; een zuidraam of 's zomers buiten. Bij weinig licht wordt de zuil dunner aan de top.",
        "In de zomer eens per 1-2 weken grondig water als de grond droog is; in de winter droog houden.",
        "Droge lucht is prima.",
        "Groeiseizoen 20-30°C; winterrust koel (5-12°C) en droog.",
        "Eens per maand in voorjaar en zomer met cactusvoeding.",
        "Om de 2-3 jaar in een zware, stabiele pot met cactusgrond - de zuil wordt snel kopzwaar.",
        "Een insnoering in de zuil ontstaat door een donkere of te warme winter; rot aan de voet door te veel water.",
    ),
    "Fishhook Barrel Cactus": (
        "Volle zon; hoe feller, hoe mooier de rode, gehaakte stekels.",
        "In de zomer eens per 2-3 weken water geven als de grond helemaal droog is; in de winter droog houden.",
        "Droge lucht is prima.",
        "Groeiseizoen 20-32°C; winterrust koel (5-12°C) en droog.",
        "Eens per maand in voorjaar en zomer met cactusvoeding op halve sterkte.",
        "Om de 3-4 jaar in minerale cactusgrond. Pas op: de haakstekels blijven makkelijk in huid en kleding hangen - gebruik dikke handschoenen.",
        "Rot aan de voet = te veel water; een scheve, smallere groei = te weinig licht.",
    ),
    "Snake Plant": (
        "Verdraagt bijna alles, van een donkere hoek tot een zonnig raam. In helder licht groeit hij het snelst en blijven de strepen het duidelijkst.",
        "Laat de grond helemaal opdrogen; in de zomer ongeveer eens per 2-3 weken, in de winter eens per 4-6 weken. Giet nooit water in het hart van de bladrozet. Te veel water is de enige echte manier om deze plant te verliezen.",
        "Droge kamerlucht is geen probleem.",
        "Ideaal 18-27°C; niet onder 10°C. Koude plus natte grond geeft snel rot.",
        "Eens per maand van april tot september met kamerplanten- of cactusvoeding op halve sterkte.",
        "Groeit graag krap; verpot om de 2-3 jaar (of als de pot barst) in cactusgrond gemengd met potgrond, in een zware pot. Deel grote pollen bij het verpotten.",
        "Zachte, omvallende bladeren met een muffe geur wijzen op wortelrot - snijd gezonde stukken af en stek ze. Bruine, droge punten zijn onschuldig; knip ze eventueel schuin bij.",
    ),
    "Cylindrical Snake Plant": (
        "Helder licht tot halfschaduw; verdraagt weinig licht, maar groeit dan nauwelijks.",
        "Laat de grond volledig opdrogen - ongeveer eens per 2-3 weken in de zomer, eens per 4-6 weken in de winter. Nooit water tussen de bladeren laten staan.",
        "Droge lucht is prima.",
        "Ideaal 18-27°C; niet onder 10°C.",
        "Eens per maand in voorjaar en zomer met verdunde cactusvoeding.",
        "Om de 2-3 jaar in cactusgrond in een zware pot. Gevlochten exemplaren niet losmaken; nieuwe scheuten komen uit de grond.",
        "Gerimpelde bladeren = lang te droog; zachte, bruine voet = te nat. Vlechtwerk kan onderaan vocht vasthouden, dus niet over de plant gieten.",
    ),
    "ZZ Plant": (
        "Verdraagt weinig licht goed, maar groeit sneller en voller in helder, indirect licht. Vermijd felle middagzon, die geeft gele vlekken.",
        "De dikke wortelknollen slaan water op: laat de grond helemaal opdrogen. In de zomer ongeveer eens per 2-3 weken, in de winter eens per maand of minder.",
        "Normale kamerlucht is prima.",
        "Ideaal 18-26°C; niet onder 12°C.",
        "Eens per maand in voorjaar en zomer met kamerplantenvoeding op halve sterkte.",
        "Om de 2-3 jaar, als de knollen de pot bijna laten barsten, in goed drainerende potgrond met perliet. Deel de knollen om te vermeerderen.",
        "Gele stelen en zachte knollen = te veel water. Bladval bij weinig licht is normaal; nieuwe stelen komen vanzelf. Draag handschoenen bij het snoeien: het sap irriteert.",
    ),
    "Ponytail Palm": (
        "Veel licht met directe zon; een zuid- of westraam is ideaal. Bij weinig licht blijft hij wel leven, maar groeit hij nauwelijks.",
        "De dikke stamvoet slaat water op: laat de grond helemaal opdrogen. In de zomer ongeveer eens per 2-3 weken, in de winter eens per 4-6 weken.",
        "Droge lucht is prima.",
        "Ideaal 18-27°C; in de winter koeler (10-15°C) en droger mag.",
        "Eens per maand in voorjaar en zomer met verdunde cactus- of kamerplantenvoeding.",
        "Groeit graag krap; verpot alleen om de 3-4 jaar, in een ondiepe, zware pot met cactusgrond.",
        "Een zachte, ingedeukte stamvoet wijst op rot door te veel water. Bruine bladpunten zijn meestal onschuldig (droge lucht of zout in het water).",
    ),
    "Yucca Cane": (
        "Zo licht mogelijk, met directe zon; een zuidraam of 's zomers buiten op het balkon. Bij te weinig licht worden de nieuwe bladeren dun en slap.",
        "Laat de bovenste helft van de grond opdrogen; in de zomer ongeveer eens per 7-10 dagen, in de winter eens per 3-4 weken.",
        "Droge kamerlucht is prima.",
        "Ideaal 18-26°C; een koelere winter (10-15°C) is juist goed. Verdraagt kort een paar graden boven nul.",
        "Van april tot september elke 2-4 weken met kamerplantenvoeding.",
        "Om de 2-3 jaar in een zware pot met potgrond met extra zand/perliet. Te lange stammen kun je in het voorjaar inkorten; de stomp loopt opnieuw uit.",
        "Een zachte stam wijst op rot door te veel water; bruine bladpunten op droge lucht of kalkrijk water; onderste bladeren die vergelen zijn normaal.",
    ),
    "Sago Palm": (
        "Veel helder licht met wat directe zon; draai de pot regelmatig zodat de bladkroon symmetrisch blijft.",
        "Laat de bovenste helft van de grond opdrogen; in de zomer ongeveer eens per 1-2 weken, in de winter eens per 3-4 weken. Nooit water in de kruin laten staan.",
        "Normale kamerlucht is prima.",
        "Ideaal 18-25°C; in de winter koeler (10-15°C) mag.",
        "Eens per maand in voorjaar en zomer met palm- of kamerplantenvoeding op halve sterkte.",
        "Groeit zeer langzaam; verpot alleen om de 3-5 jaar in goed drainerende potgrond met zand. Draag handschoenen - alle delen zijn zeer giftig.",
        "Gele bladeren kunnen wijzen op te veel water of magnesiumgebrek; wit gestippelde bladeren op schildluis.",
    ),
    "Cast Iron Plant": (
        "Kan in een vrij donkere hoek staan en is daarmee een van de beste planten voor weinig licht. Directe zon verbrandt de bladeren.",
        "Laat de bovenste 3-5 cm opdrogen; ongeveer eens per 1-2 weken in de zomer, eens per 3 weken in de winter.",
        "Niet kieskeurig; veeg de grote bladeren af en toe af met een vochtige doek.",
        "Verdraagt veel: 7-25°C. Ook geschikt voor koele hallen en slaapkamers.",
        "Eens per maand in voorjaar en zomer met kamerplantenvoeding op halve sterkte; te veel voeding laat de bontheid verdwijnen.",
        "Groeit langzaam; verpot om de 3-4 jaar in het voorjaar en deel dan eventueel de wortelstok.",
        "Bruine plekken op het blad komen door directe zon of te veel water; spint kan optreden bij warme, droge lucht.",
    ),
    "Aloe Vera": (
        "Veel licht met directe zon; een zuid- of westraam. Bij te weinig licht worden de bladeren plat, slap en hangen ze.",
        "Laat de grond volledig opdrogen; in de zomer ongeveer eens per 2-3 weken, in de winter eens per maand. Geef nooit water in de rozet.",
        "Droge lucht is prima.",
        "Ideaal 18-27°C; in de winter koeler (10-15°C) mag, niet onder 5°C.",
        "Eens per maand in voorjaar en zomer met cactusvoeding op halve sterkte.",
        "Om de 2 jaar in het voorjaar in een brede, zware pot met cactusgrond. Uitlopers (kindjes) kun je dan losmaken en apart potten.",
        "Bruine, zachte bladeren = te veel water; roodbruine verkleuring = te veel felle zon of kou; dunne, bleke bladeren = te weinig licht.",
    ),
    "Lace Aloe": (
        "Helder licht met wat directe zon; verdraagt ook halfschaduw beter dan Aloe vera.",
        "Laat de grond grotendeels opdrogen; eens per 2 weken in de zomer, eens per maand in de winter. Geen water in de rozet.",
        "Droge lucht is prima.",
        "Ideaal 15-25°C; verdraagt een koele winter tot ongeveer 5°C mits droog.",
        "Eens per maand in voorjaar en zomer met verdunde cactusvoeding.",
        "Om de 2 jaar in cactusgrond; de vele uitlopers kun je makkelijk scheiden.",
        "Zachte, bruine bladvoeten = te nat; bladpunten die rood kleuren = veel zon (onschuldig).",
    ),
    "Agave": (
        "Volle zon, zoveel mogelijk; een zuidraam of 's zomers buiten op het terras.",
        "Laat de grond volledig opdrogen; in de zomer eens per 2-3 weken, in de winter vrijwel niet.",
        "Droge lucht is ideaal.",
        "Groeiseizoen 18-30°C; winterrust koel (5-10°C) en droog.",
        "Eens per maand in voorjaar en zomer met cactusvoeding op halve sterkte.",
        "Om de 2-3 jaar in een zware, brede pot met grove cactusgrond. Knip eventueel de scherpe eindpunten af met een schaar om verwondingen te voorkomen; draag handschoenen (sap irriteert).",
        "Rot aan de voet door te veel water in de winter; schildluis op de bladonderkant.",
    ),
}
